import re
from typing import Any, Callable, Dict, List, Optional, Tuple, Type

import dspy
import tiktoken
from dspy.signatures.signature import Signature, ensure_signature

from src.engine.components.code_act_instruction_template import (
    CODE_AGENT_INSTRUCTION_TEMPLATE,
)
from src.engine.tools.primordial.python_interpreter import (
    AUTHORIZED_FUNCTIONS,
    get_python_interpreter,
)


def parse_code_blobs(text: str) -> str:
    """
    Extract Python code from markdown code blocks.

    Replaces smolagents.utils.parse_code_blobs functionality.

    Args:
        text: Text containing markdown code blocks

    Returns:
        Concatenated Python code from all code blocks
    """
    # Find all code blocks with ```python or just ```
    pattern = r"```(?:python)?\s*\n(.*?)\n```"
    matches = re.findall(pattern, text, re.DOTALL)

    if matches:
        # Join all code blocks with newlines
        return "\n\n".join(matches)
    else:
        # If no code blocks found, assume the entire text is Python code
        # This handles cases where LLM returns raw Python code without markdown
        return text.strip()


class CodeAct(dspy.Module):
    """A dspy.Module that acts as a code-generating agent."""

    def __init__(
        self,
        signature: str | Type[Signature],
        tools: Optional[List[Callable]] = None,
        max_iters: int = 4,
        code_prefix: Optional[str] = None,
    ):
        """
        Initializes the CodeAgent.

        Args:
            signature (str | Type[Signature]): The signature for the overall task,
                either as a string or a dspy.Signature class.
            tools (List[Callable], optional): A list of tools to make available
                to the Python interpreter.
            max_iters (int): The maximum number of code generation-execution loops.
        """
        super().__init__()
        self.signature = ensure_signature(signature)
        self.max_iters = max_iters
        self.last_output_python_interpreter: Optional[Any] = None
        self.code_prefix = code_prefix
        self._update_tools(tools=tools)

    def _update_tools(self, tools: Optional[List[Callable]] = None):
        """
        Update the tools the agent can use. This will update the signature, setup the Python interpreter to accept these tools, and setup the prediction module.
        """

        self.tools = tools or []
        self._setup_interpreter()
        self._prepare_agent_signatures()
        self._setup_prediction_modules()

    def _update_code_prefix(self, code_prefix: Optional[str]):
        """
        Update the code prefix (that will be added to each bloc of code before passing it to the Python Interpreter.
        """
        self.code_prefix = code_prefix

    def _setup_interpreter(self):
        """Initializes the Python interpreter and associated tool."""
        self.additional_authorized_functions = AUTHORIZED_FUNCTIONS.copy()
        # No import restrictions - all imports are allowed
        for tool in self.tools:
            self.additional_authorized_functions[tool.__name__] = tool
        python_interpreter = get_python_interpreter(
            additional_authorized_functions=self.additional_authorized_functions,
        )

        self.python_interpreter = dspy.Tool(
            func=python_interpreter,
            name="python_interpreter",
            desc="Python interpreter to evaluate the code generated by the CodeAgent.",
        )

    def _build_tools_description(self) -> str:
        """Builds the tools description for the prompt."""
        tools_description = ""
        if self.tools:
            for tool in self.tools:
                docstring = getattr(tool, "__doc__", "No description available.")
                # Clean up the docstring formatting and remove code blocks
                docstring_lines = []
                in_code_block = False
                for line in docstring.strip().split("\n"):
                    line = line.strip()
                    # Skip code block markers and content
                    if line.startswith("```"):
                        in_code_block = not in_code_block
                        continue
                    if not in_code_block:
                        docstring_lines.append(line)

                docstring = " ".join(docstring_lines)
                tools_description += f"\n- `{tool.__name__}`: {docstring}"
        return tools_description

    def _build_output_fields_description(self) -> str:
        """Builds the description of the output fields."""
        output_descriptions = []
        for name, field in self.output_fields.items():
            type_repr = field.annotation
            # Access description from json_schema_extra
            description = getattr(field, "json_schema_extra", {}).get(
                "desc", "No description available."
            )
            # Format the output description
            output_descriptions.append(f"- {name}: {type_repr} - {description}")
        return "\n".join(output_descriptions)

    def _build_code_act_instructions(self) -> str:
        """Builds the instruction prompt from template with variable substitution."""
        return CODE_AGENT_INSTRUCTION_TEMPLATE.format(
            tool_description=self.tool_description,
            task_instructions=self.task_instructions,
            output_fields_description=self.output_fields_description,
        )

    def _prepare_agent_signatures(self):
        """Prepares the DSPy signatures for the agent's actions."""
        # Extract useful informations from the signature
        self.task_instructions = self.signature.instructions  # type: ignore
        self.input_fields = self.signature.input_fields  # type: ignore
        self.output_fields = self.signature.output_fields  # type: ignore

        self.tool_description = self._build_tools_description()
        self.output_fields_description = self._build_output_fields_description()

        # Internal signature for the generation loop
        self.code_act_instructions = self._build_code_act_instructions()

        # The internal module for generating thought and code
        self.code_act_signature = (
            dspy.Signature(
                {
                    **self.input_fields  # type: ignore
                },
                instructions=self.code_act_instructions,
            )
            .append(
                "trajectory",
                dspy.InputField(
                    desc="Your execution history, consisting of your past thoughts, the code you wrote, and the execution results."
                ),
                type_=str,
            )
            .append(
                "thought",
                dspy.OutputField(desc="Your reasoning and plan for the next step."),
                type_=str,
            )
            .append(
                "python_code",
                dspy.OutputField(
                    desc="The Python code to execute to make progress on the task. Leave empty if you're ready to provide the final answer."
                ),
                type_=str,
            )
        )

        # Add the original output fields from the signature to enable completion
        for field_name, field_info in self.output_fields.items():
            self.code_act_signature = self.code_act_signature.append(
                field_name,
                field_info,
                type_=field_info.annotation
                if hasattr(field_info, "annotation")
                else str,
            )

    def _setup_prediction_modules(self):
        """Sets up the DSPy prediction modules."""
        # Set up the iterative code generation module
        self.code_act = dspy.Predict(self.code_act_signature)

    def _estimate_nb_tokens(self, text: str) -> int:
        """
        Estimates the number of tokens for a given string using tiktoken.

        Args:
            text (str): The text to tokenize and count tokens for.

        Returns:
            int: The estimated number of tokens.
        """
        # Use the cl100k_base encoding which is used by GPT-4 and GPT-3.5-turbo
        encoding = tiktoken.get_encoding("cl100k_base")
        tokens = encoding.encode(text)
        return len(tokens)

    def _check_for_completion(
        self, prediction
    ) -> Tuple[bool, Optional[Dict[str, Any]]]:
        """Check if agent has populated target output fields (excluding internal fields)."""
        extracted_outputs = {}

        # Only check the original output fields from the signature (not internal ones)
        # Internal fields are: thought, python_code, trajectory
        internal_fields = {"thought", "python_code", "trajectory"}

        for field_name, field_info in self.output_fields.items():
            if field_name not in internal_fields and hasattr(prediction, field_name):
                value = getattr(prediction, field_name)
                # All fields are now required strings, so just check for non-empty values
                if value is not None and value != "":
                    extracted_outputs[field_name] = value

        # Complete if all required non-internal fields populated
        required_fields = [
            field for field in self.output_fields.keys() if field not in internal_fields
        ]
        is_complete = len(required_fields) > 0 and all(
            field in extracted_outputs for field in required_fields
        )

        return is_complete, extracted_outputs if is_complete else None

    def forward(self, **kwargs) -> dspy.Prediction:
        """
        Executes the CodeAgent's thought-code-execute loop.

        Args:
            **kwargs: Input fields defined in the user-provided signature.

        Returns:
            dspy.Prediction: An object containing the final answer.
        """
        trajectory: List[tuple[str, str, str]] = []

        for iteration in range(self.max_iters):
            trajectory_item, should_break, current_prediction = (
                self._execute_code_act_loop(trajectory, **kwargs)
            )
            trajectory.append(trajectory_item)

            # Only check for completion if the loop indicated we should break
            # (This means no code was executed, and completion was detected in _execute_code_act_loop)
            if should_break and current_prediction:
                # Check if this break was due to completion
                is_complete, extracted_outputs = self._check_for_completion(
                    current_prediction
                )
                if is_complete:
                    from src.engine.util import get_logger

                    logger = get_logger("CodeAct", log_level="INFO")
                    logger.debug(
                        f"Task completed via output field detection at iteration {iteration + 1}"
                    )
                    return dspy.Prediction(**extracted_outputs)
                # If should_break but not complete, agent is stuck - break anyway
                break
            elif should_break:
                # Break without completion (agent stuck)
                break

        # No more automatic result extraction - agent must populate output fields explicitly
        return dspy.Prediction()

    def _execute_code_act_loop(
        self, trajectory: List[tuple[str, str, str]], **kwargs
    ) -> Tuple[Tuple[str, str, str], bool, Optional[dspy.Prediction]]:
        """Executes a single step of the agent's loop."""
        str_trajectory = self._format_trajectory(trajectory)

        # Generate thought and code
        prediction = self.code_act(trajectory=str_trajectory, **kwargs)
        thought = getattr(prediction, "thought", "")
        python_code = getattr(prediction, "python_code", "")

        # Check completion logic: prioritize code execution over completion
        if python_code and python_code.strip():
            # Agent provided code - execute it (iterative mode)
            # Even if output fields are populated, we execute code first
            pass  # Continue to code execution
        else:
            # No code provided - check if agent has completed by populating output fields
            is_complete, extracted_outputs = self._check_for_completion(prediction)
            if is_complete:
                # Agent has provided final answer in output fields without code
                observation = (
                    "Task completed: Agent provided final answer in output fields."
                )
                return (thought, python_code, observation), True, prediction
            else:
                # No code and no completion - agent is stuck
                observation = "The agent did not produce any code to complete the task."
                return (thought, python_code, observation), True, prediction

        # Prepare and execute the code for intermediate steps
        try:
            code_to_exec = parse_code_blobs(python_code)
            if self.code_prefix is not None:
                code_to_exec = self.code_prefix + "\n" + code_to_exec

        except Exception as e:
            observation = f"Error parsing your code: {e}. Please make sure to format the code correctly in a ```python ... ``` block."
            return (thought, python_code, observation), False, prediction

        try:
            logs = self.python_interpreter(python_code=code_to_exec)

            # Clear the last output since we no longer extract results from interpreter
            self.last_output_python_interpreter = None

            # Check if agent provided both code and completion fields (mixed mode warning)
            is_complete, _ = self._check_for_completion(prediction)
            if is_complete:
                warning = "\n\nWARNING: You provided both python_code and final output fields. Only the code was executed. To complete the task, provide final output fields with empty python_code in your next response."
                logs = (logs if logs else "No output from code execution.") + warning
            else:
                logs = logs if logs else "No output from code execution."

            return (thought, code_to_exec, logs), False, prediction
        except Exception as e:
            observation = f"An error occurred during execution: {e}"
            return (thought, code_to_exec, observation), False, prediction

    def _format_trajectory(self, trajectory: List[tuple[str, str, str]]) -> str:
        """Formats the trajectory into a string for the prompt."""
        if not trajectory:
            return "No execution history yet. This is the first step."

        str_trajectory = ""
        for i, (thought, code, observation) in enumerate(trajectory):
            str_trajectory += f"---[Step {i + 1}]---\n"
            str_trajectory += f"Thought: {thought}\n"
            str_trajectory += f"Code:\n```python\n{code}\n```\n"
            str_trajectory += f"Observation: {observation}\n"

        if self._estimate_nb_tokens(str_trajectory) > 2**12:
            str_trajectory += "---\nReminder: When you have the information needed, populate the required output fields directly.\n"
            str_trajectory += (
                f"REQUIRED OUTPUT FIELDS:\n{self.output_fields_description}\n---\n"
            )

        return str_trajectory


if __name__ == "__main__":
    import uuid

    import mlflow

    from src.config import LLM

    # 1. Define a simple tool
    def generate_uuid() -> str:
        """Generates a new universally unique identifier (UUID)."""
        return str(uuid.uuid4())

    # 2. Define the signature for the task
    class GenerateUUIDSignature(dspy.Signature):
        """Generates a new UUID and returns it."""

        task_description = dspy.InputField(
            desc="The user's request to generate a UUID."
        )
        generated_uuid = dspy.OutputField(desc="The newly generated UUID.")

    # 3. Configure the language model
    lm = LLM(model_name="gemini-flash-lite", provider_name="openrouter").get_llm()
    dspy.configure(lm=lm)

    # setup mlflow
    mlflow.dspy.autolog()  # type: ignore
    mlflow.set_tracking_uri("http://127.0.0.1:5000")
    mlflow.set_experiment("CodeAct")

    # 4. Instantiate the CodeAgent
    agent = CodeAct(signature=GenerateUUIDSignature, tools=[generate_uuid])

    # 5. Run the agent
    task = "I need a new UUID."
    result = agent(task_description=task)

    # 6. Print the result and validate it
    print(f"Task: {task}")
    print(f"Generated UUID: {getattr(result, 'generated_uuid')}")

    try:
        # Validate that the output is a valid UUID
        uuid.UUID(getattr(result, "generated_uuid"))
        print("Validation successful: The output is a valid UUID.")
    except (ValueError, TypeError, AttributeError):
        print("Validation failed: The output is not a valid UUID.")
