from typing import Callable, List, Optional, Type

import dspy
from dspy.primitives.program import Module
from dspy.primitives.tool import Tool
from dspy.signatures.signature import Signature, ensure_signature
from smolagents.local_python_executor import fix_final_answer_code
from smolagents.utils import parse_code_blobs

from src.engine.tools.primordial.python_interpreter import (
    AUTHORIZED_FUNCTIONS,
    AUTHORIZED_IMPORTS,
    get_python_interpreter,
)


def final_answer(outputs: dict):
    """Marks the task as complete.
    Use this function when you are confident you have collected all the necessary information to answer the user's request.
    You should pack all the required output fields into a dictionary and pass it argument to the function.
    """
    print(outputs.items())
    return outputs


class CodeAgent(Module):
    """A dspy.Module that acts as a code-generating agent."""

    def __init__(
        self,
        signature: str | Type[Signature],
        tools: Optional[List[Callable]] = None,
        max_iters: int = 4,
    ):
        """
        Initializes the CodeAgent.

        Args:
            signature (str | Type[Signature]): The signature for the overall task,
                either as a string or a dspy.Signature class.
            tools (List[Callable], optional): A list of tools to make available
                to the Python interpreter.
            max_iters (int): The maximum number of code generation-execution loops.
        """
        super().__init__()
        self.signature = ensure_signature(signature)
        self.max_iters = max_iters
        self.tools = (tools or []) + [final_answer]

        self._setup_interpreter()
        self._prepare_agent_signatures()
        self._setup_prediction_modules()

    def _setup_interpreter(self):
        """Initializes the Python interpreter and associated tool."""
        self.additional_authorized_functions = AUTHORIZED_FUNCTIONS.copy()
        self.additional_authorized_imports = AUTHORIZED_IMPORTS.copy()
        for tool in self.tools:
            self.additional_authorized_functions[tool.__name__] = tool
        python_interpreter = get_python_interpreter(
            additional_authorized_functions=self.additional_authorized_functions,
            additional_authorized_imports=self.additional_authorized_imports,
        )

        self.python_interpreter = Tool(
            func=python_interpreter,
            name="python_interpreter",
            desc="Python interpreter to evaluate the code generated by the CodeAgent.",
        )

    def _build_tools_description(self) -> str:
        """Builds the tools description for the prompt."""
        tools_description = ""
        if self.tools:
            tools_description += "\nIn addition to standard Python built-in functions, you can also use the following custom tools:\n"
            for tool in self.tools:
                docstring = getattr(tool, "__doc__", "No description available.")
                # Clean up the docstring formatting
                docstring_lines = [
                    line.strip() for line in docstring.strip().split("\n")
                ]
                docstring = " ".join(docstring_lines)
                tools_description += f"- `{tool.__name__}`: {docstring}\n"
        return tools_description

    def _build_output_fields_description(self) -> str:
        """Builds the description of the output fields."""
        output_descriptions = []
        for name, field in self.output_fields.items():
            type_repr = field.annotation
            output_descriptions.append(f"- {name}: {type_repr}")
        return "\n".join(output_descriptions)

    def _prepare_agent_signatures(self):
        """Prepares the DSPy signatures for the agent's actions."""
        # Extract useful informations from the signature
        self.task_instructions = self.signature.instructions  # type: ignore
        self.input_fields = self.signature.input_fields  # type: ignore
        self.output_fields = self.signature.output_fields  # type: ignore

        self.tool_desctiption = self._build_tools_description()
        self.output_fields_description = self._build_output_fields_description()

        # Internal signature for the generation loop
        self.code_act_instructions = f"""to execute a given task by writing and executing Python code.
For this, you have access to a Python interpreter to execute your code.

{self.tool_desctiption}

You should always stick to the following pattern to execute the task:
1.  **Think**: Analyze the user's request and your execution history (`trajectory`).
2.  **Plan**: Formulate a plan to get closer to the solution.
3.  **Code**: Write a Python code snippet to execute your plan.
4.  **Repeat**: Repeat the process until the task is solved.

When you have collected all the necessary information, call the `final_answer()` function, packing the output fields into a dictionary and passing it as argument to the function. You don't need to import this function.

Your ultimate goal is to collect enough information to provide the following outputs:
{self.output_fields_description}

Now, here the task you need to perform:
{self.task_instructions}"""

        # The internal module for generating thought and code
        self.code_act_signature = (
            dspy.Signature(
                {
                    **self.input_fields,  # type: ignore
                    "trajectory": dspy.InputField(
                        desc="Your execution history, consisting of your past thoughts, the code you wrote, and the execution results."
                    ),
                },
                instructions=self.code_act_instructions,
            )
            .append(
                "thought",
                dspy.OutputField(desc="Your reasoning and plan for the next step."),
            )
            .append(
                "python_code",
                dspy.OutputField(
                    desc="The Python code to execute to make progress on the task."
                ),
            )
        )

        # Module to extract the final answer from the trajectory
        self.output_extraction_signature = self.signature.with_instructions(
            f"Given the execution trajectory, answer the original question.\n"
            f"Original Question: {self.task_instructions}"
        ).insert(
            0,
            "trajectory",
            dspy.InputField(
                desc="The execution history of thoughts, code, and observations."
            ),
        )

    def _setup_prediction_modules(self):
        """Sets up the DSPy prediction modules."""
        self.code_act_iter = dspy.Predict(self.code_act_signature)
        self.extract = dspy.ChainOfThought(self.output_extraction_signature)

    def forward(self, **kwargs) -> dspy.Prediction:
        """
        Executes the CodeAgent's thought-code-execute loop.

        Args:
            **kwargs: Input fields defined in the user-provided signature.

        Returns:
            dspy.Prediction: An object containing the final answer.
        """
        trajectory: List[tuple[str, str, str]] = []

        for _ in range(self.max_iters):
            trajectory_item, should_break = self._execute_step(trajectory, **kwargs)
            trajectory.append(trajectory_item)
            if should_break:
                break

        str_trajectory = self._format_trajectory(trajectory)
        prediction = self.extract(trajectory=str_trajectory, **kwargs)
        return prediction

    def _execute_step(
        self, trajectory: List[tuple[str, str, str]], **kwargs
    ) -> tuple[tuple[str, str, str], bool]:
        """Executes a single step of the agent's loop."""
        str_trajectory = self._format_trajectory(trajectory)

        # Generate thought and code
        prediction = self.code_act_iter(trajectory=str_trajectory, **kwargs)
        thought = prediction.get("thought", "")
        python_code = prediction.get("python_code", "")

        if not python_code:
            # If the model generates no code, assume it's stuck and break.
            observation = "The agent did not produce any code to complete the task."
            return (thought, python_code, observation), True

        # Prepare and execute the code for intermediate steps
        try:
            code_blobs = parse_code_blobs(python_code)
            code_to_exec = fix_final_answer_code(code_blobs)
        except Exception as e:
            observation = f"Error parsing your code: {e}. Please make sure to format the code correctly in a ```python ... ``` block."
            return (thought, python_code, observation), False

        try:
            result, logs, is_final = self.python_interpreter(python_code=code_to_exec)
            observation = "Execution Logs:\n" + (logs or "No logs.")
            observation += "\n\nOutput:\n" + (repr(result) or "No output.")

            if is_final:
                return (thought, code_to_exec, observation), True
            return (thought, code_to_exec, observation), False
        except Exception as e:
            observation = f"An error occurred during execution: {e}"
            return (thought, code_to_exec, observation), False

    def _format_trajectory(self, trajectory: List[tuple[str, str, str]]) -> str:
        """Formats the trajectory into a string for the prompt."""
        if not trajectory:
            return "No execution history yet. This is the first step."

        str_trajectory = ""
        for i, (thought, code, observation) in enumerate(trajectory):
            str_trajectory += f"---[Step {i + 1}]---\n"
            str_trajectory += f"Thought: {thought}\n"
            str_trajectory += f"Code:\n```python\n{code}\n```\n"
            str_trajectory += f"Observation: {observation}\n"
        return str_trajectory


if __name__ == "__main__":
    import uuid

    import mlflow

    from src.config import LANGUAGE_MODELS

    # 1. Define a simple tool
    def generate_uuid() -> str:
        """Generates a new universally unique identifier (UUID)."""
        return str(uuid.uuid4())

    # 2. Define the signature for the task
    class GenerateUUIDSignature(dspy.Signature):
        """Generates a new UUID and returns it."""

        task_description = dspy.InputField(
            desc="The user's request to generate a UUID."
        )
        generated_uuid = dspy.OutputField(desc="The newly generated UUID.")

    def main(lm_name: str = "gemini-flash"):
        # 3. Configure the language model
        lm_info = LANGUAGE_MODELS[lm_name]
        llm = dspy.LM(
            model=lm_info.url,
            api_key=lm_info.api_key,
            max_tokens=2000,
        )
        dspy.configure(lm=llm)

        # setup mlflow
        mlflow.dspy.autolog()  # type: ignore
        mlflow.set_tracking_uri("http://127.0.0.1:5000")
        mlflow.set_experiment("CodeAgentTest")

        # 4. Instantiate the CodeAgent
        agent = CodeAgent(signature=GenerateUUIDSignature, tools=[generate_uuid])

        # 5. Run the agent
        task = "I need a new UUID."
        result = agent(task_description=task)

        # 6. Print the result and validate it
        print(f"Task: {task}")
        print(f"Generated UUID: {result.generated_uuid}")

        try:
            # Validate that the output is a valid UUID
            uuid.UUID(result.generated_uuid)
            print("Validation successful: The output is a valid UUID.")
        except (ValueError, TypeError, AttributeError):
            print("Validation failed: The output is not a valid UUID.")

    main()
