import ast
from typing import Any, Callable, List, Optional, Type

import dspy
from dspy.primitives.program import Module
from dspy.primitives.tool import Tool
from dspy.signatures.signature import Signature, ensure_signature
from smolagents.local_python_executor import fix_final_answer_code
from smolagents.utils import parse_code_blobs

from src.engine.tools.primordial.python_interpreter import (
    AUTHORIZED_FUNCTIONS,
    AUTHORIZED_IMPORTS,
    get_python_interpreter,
)
from src.engine.util import check_final_answer

from .code_act_instruction_template import CODE_AGENT_INSTRUCTION_TEMPLATE


def final_answer(outputs: dict):
    """Marks the task as complete.
    Use this function when you are confident you have collected all the necessary information to answer the user's request.
    You should pack all the required output fields into a dictionary and pass it argument to the function.
    """
    return outputs


class CodeAct(Module):
    """A dspy.Module that acts as a code-generating agent."""

    def __init__(
        self,
        signature: str | Type[Signature],
        tools: Optional[List[Callable]] = None,
        max_iters: int = 4,
        code_prefix: Optional[str] = None,
    ):
        """
        Initializes the CodeAgent.

        Args:
            signature (str | Type[Signature]): The signature for the overall task,
                either as a string or a dspy.Signature class.
            tools (List[Callable], optional): A list of tools to make available
                to the Python interpreter.
            max_iters (int): The maximum number of code generation-execution loops.
        """
        super().__init__()
        self.signature = ensure_signature(signature)
        self.max_iters = max_iters
        self.last_output_python_interpreter: Optional[Any] = None
        self.code_prefix = code_prefix
        self._update_tools(tools=tools)

    def _update_tools(self, tools: Optional[List[Callable]] = None):
        """
        Update the tools the agent can use. This will update the signature, setup the Python interpreter to accept these tools, and setup the prediction module.
        """

        self.tools = (tools or []) + [final_answer]
        self._setup_interpreter()
        self._prepare_agent_signatures()
        self._setup_prediction_modules()

    def _update_code_prefix(self, code_prefix: Optional[str]):
        """
        Update the code prefix (that will be added to each bloc of code before passing it to the Python Interpreter.
        """
        self.code_prefix = code_prefix

    def _setup_interpreter(self):
        """Initializes the Python interpreter and associated tool."""
        self.additional_authorized_functions = AUTHORIZED_FUNCTIONS.copy()
        self.additional_authorized_imports = AUTHORIZED_IMPORTS.copy()
        for tool in self.tools:
            self.additional_authorized_functions[tool.__name__] = tool
        python_interpreter = get_python_interpreter(
            additional_authorized_functions=self.additional_authorized_functions,
            additional_authorized_imports=self.additional_authorized_imports,
        )

        self.python_interpreter = Tool(
            func=python_interpreter,
            name="python_interpreter",
            desc="Python interpreter to evaluate the code generated by the CodeAgent.",
        )

    def _build_tools_description(self) -> str:
        """Builds the tools description for the prompt."""
        tools_description = ""
        if self.tools:
            for tool in self.tools:
                docstring = getattr(tool, "__doc__", "No description available.")
                # Clean up the docstring formatting and remove code blocks
                docstring_lines = []
                in_code_block = False
                for line in docstring.strip().split("\n"):
                    line = line.strip()
                    # Skip code block markers and content
                    if line.startswith("```"):
                        in_code_block = not in_code_block
                        continue
                    if not in_code_block:
                        docstring_lines.append(line)

                docstring = " ".join(docstring_lines)
                tools_description += f"\n- `{tool.__name__}`: {docstring}"
        return tools_description

    def _build_output_fields_description(self) -> str:
        """Builds the description of the output fields."""
        output_descriptions = []
        for name, field in self.output_fields.items():
            type_repr = field.annotation
            # Access description from json_schema_extra
            description = field.json_schema_extra.get(
                "desc", "No description available."
            )
            output_descriptions.append(f"- {name}: {type_repr} - {description}")
        return "\n".join(output_descriptions)

    def _build_code_act_instructions(self) -> str:
        """Builds the instruction prompt from template with variable substitution."""
        return CODE_AGENT_INSTRUCTION_TEMPLATE.format(
            tool_description=self.tool_description,
            task_instructions=self.task_instructions,
            output_fields_description=self.output_fields_description,
        )

    def _prepare_agent_signatures(self):
        """Prepares the DSPy signatures for the agent's actions."""
        # Extract useful informations from the signature
        self.task_instructions = self.signature.instructions  # type: ignore
        self.input_fields = self.signature.input_fields  # type: ignore
        self.output_fields = self.signature.output_fields  # type: ignore

        self.tool_description = self._build_tools_description()
        self.output_fields_description = self._build_output_fields_description()

        # Internal signature for the generation loop
        self.code_act_instructions = self._build_code_act_instructions()

        # The internal module for generating thought and code
        self.code_act_signature = (
            dspy.Signature(
                {
                    **self.input_fields  # type: ignore
                },
                instructions=self.code_act_instructions,
            )
            .append(
                "trajectory",
                dspy.InputField(
                    desc="Your execution history, consisting of your past thoughts, the code you wrote, and the execution results."
                ),
                type_=str,
            )
            .append(
                "thought",
                dspy.OutputField(desc="Your reasoning and plan for the next step."),
                type_=str,
            )
            .append(
                "python_code",
                dspy.OutputField(
                    desc="The Python code to execute to make progress on the task."
                ),
                type_=str,
            )
        )

    def _setup_prediction_modules(self):
        """Sets up the DSPy prediction modules."""
        # Set up the iterative code generation module
        self.code_act = dspy.Predict(self.code_act_signature)

    def forward(self, **kwargs) -> dspy.Prediction:
        """
        Executes the CodeAgent's thought-code-execute loop.

        Args:
            **kwargs: Input fields defined in the user-provided signature.

        Returns:
            dspy.Prediction: An object containing the final answer.
        """
        trajectory: List[tuple[str, str, str]] = []

        for _ in range(self.max_iters):
            trajectory_item, should_break = self._execute_code_act_loop(
                trajectory, **kwargs
            )
            trajectory.append(trajectory_item)
            if should_break:
                break

        # Check if the last output from the python_interpreter matches the signature.
        prediction = dspy.Prediction()
        if self.last_output_python_interpreter is not None and check_final_answer(
            self.last_output_python_interpreter, self.signature
        ):
            if not isinstance(self.last_output_python_interpreter, dict):
                output = ast.literal_eval(self.last_output_python_interpreter)
                prediction = dspy.Prediction(**output)

        return prediction

    def _execute_code_act_loop(
        self, trajectory: List[tuple[str, str, str]], **kwargs
    ) -> tuple[tuple[str, str, str], bool]:
        """Executes a single step of the agent's loop."""
        str_trajectory = self._format_trajectory(trajectory)

        # Generate thought and code
        prediction = self.code_act(trajectory=str_trajectory, **kwargs)
        thought = prediction.get("thought", "")
        python_code = prediction.get("python_code", "")

        if not python_code:
            # If the model generates no code, assume it's stuck and break.
            observation = "The agent did not produce any code to complete the task."
            return (thought, python_code, observation), True

        # Prepare and execute the code for intermediate steps
        try:
            code_blobs = parse_code_blobs(python_code)
            code_to_exec = fix_final_answer_code(code_blobs)
            if self.code_prefix is not None:
                code_to_exec = self.code_prefix + "\n" + code_to_exec

        except Exception as e:
            observation = f"Error parsing your code: {e}. Please make sure to format the code correctly in a ```python ... ``` block."
            return (thought, python_code, observation), False

        try:
            result, logs, is_final = self.python_interpreter(python_code=code_to_exec)

            # Store the last output from the python interpreter
            self.last_output_python_interpreter = result

            observation = "Execution Logs:\n" + (logs or "No logs.")
            observation += "\n\nOutput:\n" + (repr(result) or "No output.")

            if is_final:
                return (thought, code_to_exec, observation), True
            return (thought, code_to_exec, observation), False
        except Exception as e:
            observation = f"An error occurred during execution: {e}"
            return (thought, code_to_exec, observation), False

    def _format_trajectory(self, trajectory: List[tuple[str, str, str]]) -> str:
        """Formats the trajectory into a string for the prompt."""
        if not trajectory:
            return "No execution history yet. This is the first step."

        str_trajectory = ""
        for i, (thought, code, observation) in enumerate(trajectory):
            str_trajectory += f"---[Step {i + 1}]---\n"
            str_trajectory += f"Thought: {thought}\n"
            str_trajectory += f"Code:\n```python\n{code}\n```\n"
            str_trajectory += f"Observation: {observation}\n"
        return str_trajectory


if __name__ == "__main__":
    import uuid

    import mlflow

    from src.config import LANGUAGE_MODELS

    # 1. Define a simple tool
    def generate_uuid() -> str:
        """Generates a new universally unique identifier (UUID)."""
        return str(uuid.uuid4())

    # 2. Define the signature for the task
    class GenerateUUIDSignature(dspy.Signature):
        """Generates a new UUID and returns it."""

        task_description = dspy.InputField(
            desc="The user's request to generate a UUID."
        )
        generated_uuid = dspy.OutputField(desc="The newly generated UUID.")

    # 3. Configure the language model
    lm_name = "qwen3-8b"
    lm_info = LANGUAGE_MODELS[lm_name]
    llm = dspy.LM(
        model=lm_info.url,
        api_key=lm_info.api_key,
        max_tokens=2000,
    )
    dspy.configure(lm=llm)

    # setup mlflow
    mlflow.dspy.autolog()  # type: ignore
    mlflow.set_tracking_uri("http://127.0.0.1:5000")
    mlflow.set_experiment("CodeAct")

    # 4. Instantiate the CodeAgent
    agent = CodeAct(signature=GenerateUUIDSignature, tools=[generate_uuid])

    # 5. Run the agent
    task = "I need a new UUID."
    result = agent(task_description=task)

    # 6. Print the result and validate it
    print(f"Task: {task}")
    print(f"Generated UUID: {result.generated_uuid}")

    try:
        # Validate that the output is a valid UUID
        uuid.UUID(result.generated_uuid)
        print("Validation successful: The output is a valid UUID.")
    except (ValueError, TypeError, AttributeError):
        print("Validation failed: The output is not a valid UUID.")
