# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def ACCToolAssessor(self, rule_title: str,rule_code: str,rule_description: str,question: str,training_model_name: str,training_expected_guids: typing.List[str],training_predicted_guids: typing.List[str],training_tp: int,training_fp: int,training_fn: int,training_f1: float,validation_model_name: str,validation_expected_count: int,validation_predicted_count: int,validation_tp: int,validation_fp: int,validation_fn: int,validation_f1: float,tool_name: str,tool_implementation: str,execution_log: str,retry_count: int,previous_hints: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.ACCToolAssessment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ACCToolAssessor(rule_title=rule_title,rule_code=rule_code,rule_description=rule_description,question=question,training_model_name=training_model_name,training_expected_guids=training_expected_guids,training_predicted_guids=training_predicted_guids,training_tp=training_tp,training_fp=training_fp,training_fn=training_fn,training_f1=training_f1,validation_model_name=validation_model_name,validation_expected_count=validation_expected_count,validation_predicted_count=validation_predicted_count,validation_tp=validation_tp,validation_fp=validation_fp,validation_fn=validation_fn,validation_f1=validation_f1,tool_name=tool_name,tool_implementation=tool_implementation,execution_log=execution_log,retry_count=retry_count,previous_hints=previous_hints,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ACCToolAssessor", args={
                "rule_title": rule_title,"rule_code": rule_code,"rule_description": rule_description,"question": question,"training_model_name": training_model_name,"training_expected_guids": training_expected_guids,"training_predicted_guids": training_predicted_guids,"training_tp": training_tp,"training_fp": training_fp,"training_fn": training_fn,"training_f1": training_f1,"validation_model_name": validation_model_name,"validation_expected_count": validation_expected_count,"validation_predicted_count": validation_predicted_count,"validation_tp": validation_tp,"validation_fp": validation_fp,"validation_fn": validation_fn,"validation_f1": validation_f1,"tool_name": tool_name,"tool_implementation": tool_implementation,"execution_log": execution_log,"retry_count": retry_count,"previous_hints": previous_hints,
            })
            return typing.cast(types.ACCToolAssessment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str],previous_attempts: typing.Optional[str],is_final_iteration: bool,available_tools_docs: typing.Optional[str] = None,available_library_docs: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.NewHelperFunction"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.HelperFunctionCreator(history=history,example_question=example_question,example_answer=example_answer,example_bim_model=example_bim_model,other_bim_models_for_testing=other_bim_models_for_testing,function_name=function_name,function_description=function_description,is_enhancement=is_enhancement,existing_implementation=existing_implementation,previous_attempts=previous_attempts,is_final_iteration=is_final_iteration,available_tools_docs=available_tools_docs,available_library_docs=available_library_docs,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="HelperFunctionCreator", args={
                "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,"is_final_iteration": is_final_iteration,"available_tools_docs": available_tools_docs,"available_library_docs": available_library_docs,
            })
            return typing.cast(typing.Union["types.CodeAction", "types.NewHelperFunction"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ACCToolAssessor(self, rule_title: str,rule_code: str,rule_description: str,question: str,training_model_name: str,training_expected_guids: typing.List[str],training_predicted_guids: typing.List[str],training_tp: int,training_fp: int,training_fn: int,training_f1: float,validation_model_name: str,validation_expected_count: int,validation_predicted_count: int,validation_tp: int,validation_fp: int,validation_fn: int,validation_f1: float,tool_name: str,tool_implementation: str,execution_log: str,retry_count: int,previous_hints: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ACCToolAssessment, types.ACCToolAssessment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ACCToolAssessor", args={
            "rule_title": rule_title,"rule_code": rule_code,"rule_description": rule_description,"question": question,"training_model_name": training_model_name,"training_expected_guids": training_expected_guids,"training_predicted_guids": training_predicted_guids,"training_tp": training_tp,"training_fp": training_fp,"training_fn": training_fn,"training_f1": training_f1,"validation_model_name": validation_model_name,"validation_expected_count": validation_expected_count,"validation_predicted_count": validation_predicted_count,"validation_tp": validation_tp,"validation_fp": validation_fp,"validation_fn": validation_fn,"validation_f1": validation_f1,"tool_name": tool_name,"tool_implementation": tool_implementation,"execution_log": execution_log,"retry_count": retry_count,"previous_hints": previous_hints,
        })
        return baml_py.BamlStream[stream_types.ACCToolAssessment, types.ACCToolAssessment](
          __result__,
          lambda x: typing.cast(stream_types.ACCToolAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ACCToolAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str],previous_attempts: typing.Optional[str],is_final_iteration: bool,available_tools_docs: typing.Optional[str] = None,available_library_docs: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], typing.Union["types.CodeAction", "types.NewHelperFunction"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="HelperFunctionCreator", args={
            "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,"is_final_iteration": is_final_iteration,"available_tools_docs": available_tools_docs,"available_library_docs": available_library_docs,
        })
        return baml_py.BamlStream[typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], typing.Union["types.CodeAction", "types.NewHelperFunction"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.CodeAction", "types.NewHelperFunction"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ACCToolAssessor(self, rule_title: str,rule_code: str,rule_description: str,question: str,training_model_name: str,training_expected_guids: typing.List[str],training_predicted_guids: typing.List[str],training_tp: int,training_fp: int,training_fn: int,training_f1: float,validation_model_name: str,validation_expected_count: int,validation_predicted_count: int,validation_tp: int,validation_fp: int,validation_fn: int,validation_f1: float,tool_name: str,tool_implementation: str,execution_log: str,retry_count: int,previous_hints: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ACCToolAssessor", args={
            "rule_title": rule_title,"rule_code": rule_code,"rule_description": rule_description,"question": question,"training_model_name": training_model_name,"training_expected_guids": training_expected_guids,"training_predicted_guids": training_predicted_guids,"training_tp": training_tp,"training_fp": training_fp,"training_fn": training_fn,"training_f1": training_f1,"validation_model_name": validation_model_name,"validation_expected_count": validation_expected_count,"validation_predicted_count": validation_predicted_count,"validation_tp": validation_tp,"validation_fp": validation_fp,"validation_fn": validation_fn,"validation_f1": validation_f1,"tool_name": tool_name,"tool_implementation": tool_implementation,"execution_log": execution_log,"retry_count": retry_count,"previous_hints": previous_hints,
        }, mode="request")
        return __result__
    async def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str],previous_attempts: typing.Optional[str],is_final_iteration: bool,available_tools_docs: typing.Optional[str] = None,available_library_docs: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="HelperFunctionCreator", args={
            "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,"is_final_iteration": is_final_iteration,"available_tools_docs": available_tools_docs,"available_library_docs": available_library_docs,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def ACCToolAssessor(self, rule_title: str,rule_code: str,rule_description: str,question: str,training_model_name: str,training_expected_guids: typing.List[str],training_predicted_guids: typing.List[str],training_tp: int,training_fp: int,training_fn: int,training_f1: float,validation_model_name: str,validation_expected_count: int,validation_predicted_count: int,validation_tp: int,validation_fp: int,validation_fn: int,validation_f1: float,tool_name: str,tool_implementation: str,execution_log: str,retry_count: int,previous_hints: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ACCToolAssessor", args={
            "rule_title": rule_title,"rule_code": rule_code,"rule_description": rule_description,"question": question,"training_model_name": training_model_name,"training_expected_guids": training_expected_guids,"training_predicted_guids": training_predicted_guids,"training_tp": training_tp,"training_fp": training_fp,"training_fn": training_fn,"training_f1": training_f1,"validation_model_name": validation_model_name,"validation_expected_count": validation_expected_count,"validation_predicted_count": validation_predicted_count,"validation_tp": validation_tp,"validation_fp": validation_fp,"validation_fn": validation_fn,"validation_f1": validation_f1,"tool_name": tool_name,"tool_implementation": tool_implementation,"execution_log": execution_log,"retry_count": retry_count,"previous_hints": previous_hints,
        }, mode="stream")
        return __result__
    async def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str],previous_attempts: typing.Optional[str],is_final_iteration: bool,available_tools_docs: typing.Optional[str] = None,available_library_docs: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="HelperFunctionCreator", args={
            "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,"is_final_iteration": is_final_iteration,"available_tools_docs": available_tools_docs,"available_library_docs": available_library_docs,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))