# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (22)
# #########################################################################

class ACCToolAssessment(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Step-by-step analysis of tool execution and validation results')
    diagnosis: typing.Optional[typing.Union[typing_extensions.Literal['overfitting'], typing_extensions.Literal['missing_generalization'], typing_extensions.Literal['implementation_bug'], typing_extensions.Literal['model_difference'], typing_extensions.Literal['unknown']]] = Field(default=None, description='Root cause diagnosis:\n- overfitting: Tool relies on training-specific patterns (e.g., hardcoded values, specific element names)\n- missing_generalization: Tool misses valid cases due to incomplete logic (e.g., missing element types)\n- implementation_bug: Logic error in the tool implementation\n- model_difference: Validation model has structural differences that require different handling\n- unknown: Unable to determine cause from available information')
    improvement_hint: typing.Optional[str] = Field(default=None, description='Generic guidance for improving the tool. MUST NOT contain validation-specific GUIDs or element identifiers.\nExamples: "Consider checking all IfcSpace subtypes", "Handle spaces with multiple boundary conditions",\n"Check for classification variations in the Name property"')
    recommendation: typing.Optional[typing.Union[typing_extensions.Literal['keep_tool'], typing_extensions.Literal['retry_with_hint']]] = Field(default=None, description='Final recommendation:\n- keep_tool: Tool is good enough despite imperfect validation (F1 >= threshold or best effort reached)\n- retry_with_hint: Try creating an improved version using the improvement_hint')
    confidence: typing.Optional[typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]] = Field(default=None, description='Confidence in this diagnosis:\n- high: Clear pattern identified with strong evidence\n- medium: Likely cause identified but some uncertainty\n- low: Diagnosis is speculative due to limited information')

class AlignedQAPair(BaseModel):
    thought: typing.Optional[str] = Field(default=None, description='Analysis of the alignment between question and answer, and reasoning for any changes')
    aligned_question: typing.Optional[str] = Field(default=None, description='Question reformulated to align with answer structure and scope (or original if already aligned)')
    aligned_answer: typing.Optional[str] = Field(default=None, description='Answer with improved formatting/clarity while preserving factual content (or original if already good)')
    was_modified: typing.Optional[bool] = Field(default=None, description='Whether any modifications were made to question or answer')

class AnswerEvaluationResult(BaseModel):
    abstention: typing.Optional[bool] = Field(default=None, description='true if system explicitly declined to answer, false if answer provided')
    faithfulness: typing.Optional[types.CriterionResult] = Field(default=None, description='Are all claims grounded in valid sources for this question category?\n- Category 1: BIM data only\n- Category 2: Simple computations on BIM data\n- Category 3: Complex geometric computations from BIM data\n- Category 4: BIM data + explicitly stated assumptions\nUse \'na\' only if abstention is true.')
    completeness: typing.Optional[types.CriterionResult] = Field(default=None, description='Are all relevant facts included to fully answer the question?\nUse \'na\' if abstention is true OR question is open-ended with no objective completeness standard.')
    transparency: typing.Optional[types.CriterionResult] = Field(default=None, description='Are sources/methods explicitly disclosed for each claim?\nUse \'na\' only if abstention is true.')
    relevance: typing.Optional[types.CriterionResult] = Field(default=None, description='Does the answer directly address the question asked?\nUse \'na\' only if abstention is true.')
    justification: typing.Optional[str] = Field(default=None, description='Brief explanation (2-3 sentences) of the evaluation, especially for edge cases or borderline decisions.\nFocus on explaining any \'no\' verdicts or unusual circumstances.')

class AssessmentResult(BaseModel):
    assessment_status: typing.Optional[typing.Union[typing_extensions.Literal['ok'], typing_extensions.Literal['needs_improvement']]] = Field(default=None, description='\'ok\' if function works as expected, \'needs_improvement\' if issues found')
    assessment_details: typing.Optional[str] = Field(default=None, description='Detailed explanation of test results and any issues discovered')
    test_execution_log: typing.Optional[str] = Field(default=None, description='Log of function execution and test cases attempted')

class CategoryValidationResult(BaseModel):
    validated_category: typing.Optional[str] = Field(default=None, description='The correct category (1, 2, 3, or 4) according to the taxonomy')
    updated: typing.Optional[bool] = Field(default=None, description='Whether the category was changed from the original')
    thought: typing.Optional[str] = Field(default=None, description='Reasoning for the category classification and any changes made')

class ChunkReviewInput(BaseModel):
    chunk_type: typing.Optional[str] = None
    name: typing.Optional[str] = None
    module_path: typing.Optional[str] = None
    signature: typing.Optional[str] = None
    content: typing.Optional[str] = None

class ChunkReviewOutput(BaseModel):
    useful: typing.Optional[bool] = Field(default=None, description='Whether this chunk is useful for answering user questions about IfcOpenShell')
    reason: typing.Optional[str] = Field(default=None, description='If not useful, explain why (e.g., \'too short\', \'internal implementation detail\', \'no useful information\')')
    questions: typing.List[str] = Field(description='3-5 hypothetical questions that a user might ask that this chunk would answer')

class CodeAction(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Reasoning for next step')
    python_code: typing.Optional[str] = Field(default=None, description='Code to execute')

class ErrorAnalysisResult(BaseModel):
    error_category: typing.Optional[str] = Field(default=None, description='faulty_tool, missing_tool, other')
    function_name: typing.Optional[str] = None
    needs_new_tool: typing.Optional[bool] = None

class FaultyToolAnalysis(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Chain-of-thought analysis of the execution history to identify tool-related failures')
    faulty_tool: typing.Optional[bool] = Field(default=None, description='Whether a faulty tool was identified as the primary cause of the wrong answer')
    faulty_tool_name: typing.Optional[str] = Field(default=None, description='Name of the faulty tool (empty string if faulty_tool is false)')
    error_description: typing.Optional[str] = Field(default=None, description='Summary of the error and test cases demonstrating the failure (empty string if faulty_tool is false)')
    confidence: typing.Optional[typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]] = Field(default=None, description='Confidence level in this faulty tool identification')

class FinalAnswer(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Summary of findings')
    answer: typing.Optional[str] = Field(default=None, description='Final answer to user\'s question')
    ifc_guids: typing.List[str] = Field(description='IFC GUIDs of elements relevant to the answer. For compliance checks: include all non-compliant element GUIDs. For pairwise violations (e.g., doors too close), include GUIDs of ALL involved elements. Return an empty array [] if no violations or relevant elements are found.')

class FunctionImplementation(BaseModel):
    function_implementation: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    needs_improvement: typing.Optional[bool] = None

class HelperFunctionAssessment(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Detailed analysis of how the tool was used during execution')
    tool_was_used: typing.Optional[bool] = Field(default=None, description='Whether the tool was actually called during execution')
    tool_usage_quality: typing.Optional[typing.Union[typing_extensions.Literal['helpful'], typing_extensions.Literal['not_used'], typing_extensions.Literal['ignored'], typing_extensions.Literal['misused'], typing_extensions.Literal['harmful']]] = Field(default=None, description='Assessment of how the tool contributed to the answer:\n- helpful: Tool was used correctly and contributed to producing the correct answer\n- not_used: Tool was available but Cobbie didn\'t use it at all\n- ignored: Tool was considered/mentioned but deemed unnecessary or not applicable\n- misused: Tool was used incorrectly (wrong parameters, wrong context, misunderstood purpose)\n- harmful: Tool was used and led to incorrect results or wrong reasoning')
    usage_details: typing.Optional[str] = Field(default=None, description='Detailed explanation of tool usage patterns and outcomes:\n- If helpful: How the tool contributed to the correct answer\n- If not_used: Why the tool wasn\'t needed or what alternative approach was used\n- If ignored: Why Cobbie chose not to use it\n- If misused: What parameters were wrong or how the usage was incorrect\n- If harmful: How the tool\'s output led to the wrong answer')
    recommendation: typing.Optional[typing.Union[typing_extensions.Literal['keep_tool'], typing_extensions.Literal['discard_tool'], typing_extensions.Literal['improve_tool'], typing_extensions.Literal['unclear']]] = Field(default=None, description='Final recommendation based on usage analysis:\n- keep_tool: Tool was helpful and should be saved permanently\n- discard_tool: Tool wasn\'t useful, was harmful, or is redundant\n- improve_tool: Tool has potential but needs fixes or refinement\n- unclear: Insufficient evidence to make a confident decision (need more test cases)')
    confidence: typing.Optional[typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]] = Field(default=None, description='Confidence level in this assessment:\n- high: Clear evidence from execution history supports the assessment\n- medium: Strong indicators but some ambiguity or edge cases\n- low: Limited evidence or conflicting signals')

class ImprovedImplementation(BaseModel):
    function_implementation: typing.Optional[str] = Field(default=None, description='Updated Python source code addressing assessment issues')
    reasoning: typing.Optional[str] = Field(default=None, description='Explanation of changes made and how they address the feedback')
    changes_summary: typing.Optional[str] = Field(default=None, description='Brief summary of the main changes made')

class NewHelperFunction(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Summary of development process, testing performed, and validation results')
    function_implementation: typing.Optional[str] = Field(default=None, description='Complete Python function implementation including imports, docstring, and type hints')
    success: typing.Optional[bool] = Field(default=None, description='Whether the function is complete, tested, and ready for use')

class NewToolAnalysis(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Step-by-step analysis of the execution history to identify reusable patterns')
    action: typing.Optional[typing.Union[typing_extensions.Literal['create_new'], typing_extensions.Literal['enhance_existing'], typing_extensions.Literal['none']]] = Field(default=None, description='Decision on tool management:\n- create_new: Create a completely new helper function\n- enhance_existing: Enhance existing tool with optional parameters\n- none: No tool creation or enhancement needed')
    tool_name: typing.Optional[str] = Field(default=None, description='For create_new: Name for new function\nFor enhance_existing: Name of existing tool to enhance\nFor none: Empty string')
    tool_description: typing.Optional[str] = Field(default=None, description='For create_new: Full function specification\nFor enhance_existing: Enhancement description (what parameters to add)\nFor none: Empty string')
    existing_tool_for_enhancement: typing.Optional[str] = Field(default=None, description='Only for enhance_existing: Name of tool to enhance (same as tool_name)')

class SimilarityResult(BaseModel):
    similarity_score: typing.Optional[float] = None
    correct_answer: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None

class TestAndImproveError(BaseModel):
    error_message: typing.Optional[str] = Field(default=None, description='Detailed error description')
    iterations_completed: typing.Optional[int] = Field(default=None, description='Number of iterations completed before failure')
    final_assessment_status: typing.Optional[str] = Field(default=None, description='Last known assessment status, if any')
    partial_function_implementation: typing.Optional[str] = Field(default=None, description='Best function implementation achieved, if any')

class TestAndImproveSuccess(BaseModel):
    function_implementation: typing.Optional[str] = Field(default=None, description='Final validated function implementation')
    assessment_details: typing.Optional[str] = Field(default=None, description='Final assessment confirming function works correctly')
    iterations_used: typing.Optional[int] = Field(default=None, description='Number of iterations needed to achieve success')
    total_time_seconds: typing.Optional[float] = Field(default=None, description='Total time taken for testing and improvement')

class ToolCreationResult(BaseModel):
    function_name: typing.Optional[str] = None
    function_implementation: typing.Optional[str] = None
    success: typing.Optional[bool] = None

class ToolOptimizationResult(BaseModel):
    improvement: typing.Optional[str] = Field(default=None, description='create_new_tool, merge_existing_tools, update_existing_tool, no_action_needed')
    function_name: typing.Optional[str] = None
    function_requirements: typing.Optional[str] = None
    existing_tool_names: typing.Optional[typing.List[str]] = None

class UpdatedHelperFunction(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Analysis of the faulty function and explanation of the fixing process')
    fixed_implementation: typing.Optional[str] = Field(default=None, description='Fixed Python function implementation that addresses the identified issues')
    changes_summary: typing.Optional[str] = Field(default=None, description='Summary of the main changes made to fix the function')
    success: typing.Optional[bool] = Field(default=None, description='Whether the function was successfully fixed and is ready for use')
    test_cases_provided: typing.Optional[str] = Field(default=None, description='Test cases that can be used to verify the fix works correctly')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
