# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (3)
# #########################################################################

class ACCToolAssessment(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Step-by-step analysis of tool execution and validation results')
    diagnosis: typing.Optional[typing.Union[typing_extensions.Literal['overfitting'], typing_extensions.Literal['missing_generalization'], typing_extensions.Literal['implementation_bug'], typing_extensions.Literal['model_difference'], typing_extensions.Literal['unknown']]] = Field(default=None, description='Root cause diagnosis:\n- overfitting: Tool relies on training-specific patterns (e.g., hardcoded values, specific element names)\n- missing_generalization: Tool misses valid cases due to incomplete logic (e.g., missing element types)\n- implementation_bug: Logic error in the tool implementation\n- model_difference: Validation model has structural differences that require different handling\n- unknown: Unable to determine cause from available information')
    improvement_hint: typing.Optional[str] = Field(default=None, description='Generic guidance for improving the tool. MUST NOT contain validation-specific GUIDs or element identifiers.\nExamples: "Consider checking all IfcSpace subtypes", "Handle spaces with multiple boundary conditions",\n"Check for classification variations in the Name property"')
    recommendation: typing.Optional[typing.Union[typing_extensions.Literal['keep_tool'], typing_extensions.Literal['retry_with_hint']]] = Field(default=None, description='Final recommendation:\n- keep_tool: Tool is good enough despite imperfect validation (F1 >= threshold or best effort reached)\n- retry_with_hint: Try creating an improved version using the improvement_hint')
    confidence: typing.Optional[typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]] = Field(default=None, description='Confidence in this diagnosis:\n- high: Clear pattern identified with strong evidence\n- medium: Likely cause identified but some uncertainty\n- low: Diagnosis is speculative due to limited information')

class CodeAction(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Reasoning for next step')
    python_code: typing.Optional[str] = Field(default=None, description='Code to execute')

class NewHelperFunction(BaseModel):
    thoughts: typing.Optional[str] = Field(default=None, description='Summary of development process, testing performed, and validation results')
    function_implementation: typing.Optional[str] = Field(default=None, description='Complete Python function implementation including imports, docstring, and type hints')
    success: typing.Optional[bool] = Field(default=None, description='Whether the function is complete, tested, and ready for use')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
