# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ACCToolAssessment": types.ACCToolAssessment,
    "stream_types.ACCToolAssessment": stream_types.ACCToolAssessment,

    "types.CodeAction": types.CodeAction,
    "stream_types.CodeAction": stream_types.CodeAction,

    "types.NewHelperFunction": types.NewHelperFunction,
    "stream_types.NewHelperFunction": stream_types.NewHelperFunction,


}