# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (3)
# #########################################################################

class ACCToolAssessment(BaseModel):
    thoughts: str = Field(description='Step-by-step analysis of tool execution and validation results')
    diagnosis: typing.Union[typing_extensions.Literal['overfitting'], typing_extensions.Literal['missing_generalization'], typing_extensions.Literal['implementation_bug'], typing_extensions.Literal['model_difference'], typing_extensions.Literal['unknown']] = Field(description='Root cause diagnosis:\n- overfitting: Tool relies on training-specific patterns (e.g., hardcoded values, specific element names)\n- missing_generalization: Tool misses valid cases due to incomplete logic (e.g., missing element types)\n- implementation_bug: Logic error in the tool implementation\n- model_difference: Validation model has structural differences that require different handling\n- unknown: Unable to determine cause from available information')
    improvement_hint: str = Field(description='Generic guidance for improving the tool. MUST NOT contain validation-specific GUIDs or element identifiers.\nExamples: "Consider checking all IfcSpace subtypes", "Handle spaces with multiple boundary conditions",\n"Check for classification variations in the Name property"')
    recommendation: typing.Union[typing_extensions.Literal['keep_tool'], typing_extensions.Literal['retry_with_hint']] = Field(description='Final recommendation:\n- keep_tool: Tool is good enough despite imperfect validation (F1 >= threshold or best effort reached)\n- retry_with_hint: Try creating an improved version using the improvement_hint')
    confidence: typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']] = Field(description='Confidence in this diagnosis:\n- high: Clear pattern identified with strong evidence\n- medium: Likely cause identified but some uncertainty\n- low: Diagnosis is speculative due to limited information')

class CodeAction(BaseModel):
    thoughts: str = Field(description='Reasoning for next step')
    python_code: str = Field(description='Code to execute')

class NewHelperFunction(BaseModel):
    thoughts: str = Field(description='Summary of development process, testing performed, and validation results')
    function_implementation: str = Field(description='Complete Python function implementation including imports, docstring, and type hints')
    success: bool = Field(description='Whether the function is complete, tested, and ready for use')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
