[project]
name = "ifcanswerenginev3"
version = "0.1.0"
description = "An Engine that can answer any question related to a given BIM model in .ifc format."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arize-phoenix==8.24.0",
    "chromadb>=1.0.8",
    "dspy>=2.6.23",
    "duckduckgo-search>=8.0.1",
    "fastapi[standard]>=0.115.9",
    "gradio>=5.29.0",
    "ifcopenshell>=0.8.2",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "mermaid-magic>=0.1.4",
    "mlflow>=3.1.0",
    "mypy>=1.16.1",
    "ollama>=0.4.8",
    "openinference-instrumentation-smolagents>=0.1.11",
    "opentelemetry-exporter-otlp>=1.32.1",
    "opentelemetry-sdk>=1.32.1",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
    "scipy>=1.15.3",
    "smolagents[gradio,telemetry,toolkit]>=1.15.0",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "ty>=0.0.1a6",
]
