"""
Generated by Cursor - not reviewd yet.
"""

from smolagents.local_python_executor import (
    BASE_PYTHON_TOOLS,
    LocalPythonExecutor,
)


class PythonExecutorTool:
    def __init__(self, authorized_imports=None, static_tools=None):
        # Set defaults if not provided
        self.authorized_imports = authorized_imports or ["math", "numpy"]
        self.static_tools = static_tools or BASE_PYTHON_TOOLS.copy()
        # Create persistent state
        self.state = {}
        # Initialize executor
        self.executor = LocalPythonExecutor(
            additional_authorized_imports=self.authorized_imports
        )
        self.executor.static_tools = self.static_tools

    def evaluate_python_code(self, code: str) -> str:
        """Execute Python code and return both the result and any printed output.

        Args:
            code: The Python code to execute as a string

        Returns:
            A formatted string containing both the print outputs and return value
        """
        # Execute the code
        result, logs, is_final = self.executor(code)

        # Format the response to include both printed output and return value
        response = ""
        if logs:
            response += f"Print output:\n{logs}\n\n"

        response += f"Return value: {result}"
        return response


if __name__ == "__main__":
    import dspy
    from pydantic import BaseModel
    from dotenv import load_dotenv, find_dotenv
    import os

    load_dotenv(find_dotenv())
    ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]

    # Set up language model (LiteLLM endpoints)
    class LLM(BaseModel):
        url: str
        name: str
        api_key: str = ""

    LANGUAGE_MODELS: dict[str, LLM] = {}
    LANGUAGE_MODELS["claude"] = LLM(
        url="anthropic/claude-3-7-sonnet-latest",
        api_key=ANTHROPIC_API_KEY,
        name="claude",
    )
    llm_info: LLM = LANGUAGE_MODELS["claude"]
    lm = dspy.LM(model=llm_info.url, api_key=llm_info.api_key)
    dspy.configure(lm=lm)
    # Create the Python executor tool
    python_executor = PythonExecutorTool(
        authorized_imports=["math", "numpy", "random"],
        static_tools=BASE_PYTHON_TOOLS.copy(),
    )

    # Define a ReAct agent that can use the Python executor
    react_agent = dspy.ReAct(
        "question -> answer", tools=[python_executor.evaluate_python_code]
    )

    # Example usage
    result = react_agent(
        question="Calculate the square root of 144 and then generate 5 random numbers between 0 and that value."
    )
    print(result.answer)
