#!/usr/bin/env fish
#
# Retry error/abstained questions from the evaluation matrix.
# Reads the manifest JSON generated by generate_retry_manifest.py and runs
# each question one-by-one using --continue to append to the existing parent run.
#
# Prerequisites:
#   1. MLflow server must be running
#   2. Run: uv run scripts/generate_retry_manifest.py
#
# Usage:
#   fish scripts/retry_matrix_errors.fish
#   fish scripts/retry_matrix_errors.fish --manifest outputs/eval/retry_manifest.json
#   fish scripts/retry_matrix_errors.fish --start-from 10  # skip first 10 entries

set manifest "outputs/eval/retry_manifest.json"
set start_from 0

# ── parse arguments ──
set i 1
while test $i -le (count $argv)
    switch $argv[$i]
        case --manifest
            set i (math $i + 1)
            set manifest $argv[$i]
        case --start-from
            set i (math $i + 1)
            set start_from $argv[$i]
    end
    set i (math $i + 1)
end

if not test -f $manifest
    echo "✗ Manifest not found: $manifest"
    echo "  Run: uv run scripts/generate_retry_manifest.py"
    exit 1
end

set total (jq 'length' $manifest)
echo "═══════════════════════════════════════════════════════"
echo "  Retry matrix errors"
echo "  Manifest: $manifest"
echo "  Total entries: $total (starting from index $start_from)"
echo "═══════════════════════════════════════════════════════"

set failed 0
set succeeded 0

for idx in (seq $start_from (math $total - 1))
    set run_name (jq -r ".[$idx].run_name" $manifest)
    set parent_run_id (jq -r ".[$idx].parent_run_id" $manifest)
    set devset_index (jq -r ".[$idx].devset_index" $manifest)
    set question_id (jq -r ".[$idx].question_id" $manifest)
    set old_class (jq -r ".[$idx].old_classification" $manifest)
    set eval_args (jq -r ".[$idx].eval_args" $manifest)

    set progress (math $idx + 1)
    echo ""
    echo "▶ [$progress/$total] $run_name — question $question_id (DEVSET[$devset_index], was: $old_class)"

    # Split eval_args string into individual arguments
    set args_list (string split -- " " $eval_args)

    uv run scripts/run_evaluation.py --start $devset_index --nb-samples 1 --continue $parent_run_id $args_list

    if test $status -ne 0
        echo "  ✗ Failed. Continuing to next question."
        set failed (math $failed + 1)
    else
        echo "  ✓ Done."
        set succeeded (math $succeeded + 1)
    end
end

echo ""
echo "═══════════════════════════════════════════════════════"
echo "  Retry complete."
echo "  Succeeded: $succeeded / $total"
if test $failed -gt 0
    echo "  Failed: $failed"
end
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Clean up duplicate nested runs (keep only latest per question_id)"
echo "  2. Re-run analysis: uv run scripts/analyze_evaluation_matrix.py"
