"""
WIP -- generated by cursor -- currently not working.
Next step:
- update the innerloop of the function create_new_tool.
    - the tool_assessor needs to be dynamically created
    - add a verbose parameter and use a logger instead of these print statements

Need to:
- load the helper functions from the separate files
- implement the control flow between the agents
- review the signatures to enforce this dynamic tool selection/execution for the tool_assessor
"""

# %% Imports
# =============== Imports and config =============== #
import logging
import os
import sys
from typing import Literal, Optional
import tiktoken

import dspy
from pydantic import BaseModel
from smolagents.local_python_executor import LocalPythonExecutor

from src import FUNCTION_BOILERPLATE, LANGUAGE_MODELS, LLM, LOG_LEVEL, ROOT_PATH
from src.special_tools import query_ifcopenshell_documentation, web_search

# Set up the path
if ROOT_PATH not in sys.path:
    sys.path.append(ROOT_PATH)

# Set up the LLM for dspy
llm_info = LANGUAGE_MODELS["claude"]
lm = dspy.LM(model=llm_info.url, api_key=llm_info.api_key)
dspy.configure(lm=lm)

# Define the tools
TOOLS = [web_search, query_ifcopenshell_documentation]

# Load the overview of the documentation of IfcOpenShell
doc_path = os.path.join(ROOT_PATH, "src/special_tools/ifcopenshell_api_overview_v2.md")
with open(doc_path, "r") as file:
    IFCOPENSHELL_DOCUMENTATION_OVERVIEW = file.read()
del doc_path


# %% Types
# =============== Define Datatypes =============== #
class Result(BaseModel):
    python_code: Optional[str] = None
    assessment_status: Optional[Literal["ok", "needs_improvement"]] = None
    assessment_details: Optional[str] = None


class ModuleOutput(BaseModel):
    result: Optional[Result] = None
    status: Literal["error", "success"]
    error_msg: Optional[str] = None


# TODO Consider moving this to a dedicated file. Add docstring.
def get_logger(
    name: str = __name__,
    log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = "DEBUG",
):
    logger = logging.getLogger(name)
    handler = logging.StreamHandler()
    formatter = logging.Formatter(
        "%(asctime)s : %(levelname)s : %(name)s : %(message)s"
    )
    handler.setFormatter(formatter)
    logger.addHandler(handler)

    if log_level == "CRITICAL":
        logger.setLevel(logging.CRITICAL)
    elif log_level == "ERROR":
        logger.setLevel(logging.ERROR)
    elif log_level == "WARNING":
        logger.setLevel(logging.WARNING)
    elif log_level == "INFO":
        logger.setLevel(logging.INFO)
    else:
        logger.setLevel(logging.DEBUG)

    return logger


# %% Dynamic Tool Creation Utilities
# =============== Dynamic Tool Creation Utilities =============== #


# %% DSPy
# =============== Define ToolMaker =============== #
class NewToolSignature(dspy.Signature):
    f"""
    Create a Python function that implements the requirements using the IfcOpenShell Python library.
    This function will be used as a "tool" by an LLM-based ReAct agent to answer some user's query related to a BIM model.

    The generated function should:
    - Take at least one argument: path_ifc_file: str, which is a path to the .ifc file the function should interact with.
    - Be well-documented with docstrings and type hints

    IMPORTANT:
    - Do not make assumptions about IFC schema or data structure.
    - Use the provided tools to research proper implementation details through documentation and web search.

    Below is an overview of how the structure of the IfcOpenShell Python library. For details regarding the implementation of each available method, use the `query_ifcopenshell_documentation` tool.

    Overview:
    {IFCOPENSHELL_DOCUMENTATION_OVERVIEW}
    """

    # inputs
    function_description: str = dspy.InputField(
        desc="Detailed description of what the function should do and its requirements."
    )
    function_name: str = dspy.InputField()

    function_boilerplate: str = dspy.InputField(
        desc="This boilerplate must be included at the beginning of your code; otherwise, it will not work properly."
    )

    # outputs
    python_code: str = dspy.OutputField(
        desc="Complete code implementation (including imports from the boilerplate, any necessary helper functions, etc.) of your Python function implementation."
    )


class ToolCreator(dspy.Module):
    """Module to create a new Python function that meets the requirements."""

    def __init__(
        self,
        tools: list,
        max_iters: int = 10,
        log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = "DEBUG",
    ):
        super().__init__()
        self.tools = tools
        self.max_iters = max_iters
        self.agent = dspy.ReAct(
            signature=NewToolSignature, tools=tools, max_iters=self.max_iters
        )
        self.log_level = log_level
        self.logger = get_logger(name="ToolCreator", log_level=self.log_level)

    def forward(
        self,
        function_description: str,
        function_name: str,
        function_boilerplate: str = FUNCTION_BOILERPLATE,
    ) -> ModuleOutput:
        result = self.agent(
            function_description=function_description,
            function_name=function_name,
            function_boilerplate=function_boilerplate,
        )

        # Check if we got valid python code
        if hasattr(result, "python_code") and result.python_code:
            self.logger.info(f"function: {function_name} created successfully.")
            self.logger.debug(f"function code:\n{result.python_code}\n")
            return ModuleOutput(
                result=Result(python_code=result.python_code), status="success"
            )
        else:
            self.logger.error(
                f"Error when trying to generate code for function: {function_name}"
            )
            return ModuleOutput(
                status="error",
                error_msg=f"No valid code generated for function: {function_name}",
            )


# =============== Define ToolAssessor =============== #
class ToolAssessmentSignature(dspy.Signature):
    """
    Assess whether a generated function meets requirements and works correctly.
    Tests the function with real IFC files and evaluates code quality and functionality.
    """

    # inputs
    function_name: str = dspy.InputField(desc="Name of the function to assess")
    function_code: str = dspy.InputField(
        desc="Source code of the function implementation"
    )
    function_requirements: str = dspy.InputField(
        desc="Original requirements and description of what the function should do"
    )
    path_ifc_model: str = dspy.InputField(
        desc="Path to an IFC file for testing the function"
    )

    # outputs
    assessment_status: Literal["ok", "needs_improvement"] = dspy.OutputField(
        desc="'ok' if the tool works as expected, 'needs_improvement' if issues were found"
    )
    assessment_details: str = dspy.OutputField(
        desc="Detailed explanation of the assessment, including any issues found and improvement suggestions"
    )


class ToolAssessor(dspy.Module):
    """Module to assess the quality and functionality of generated tools."""

    def __init__(
        self,
        tools: list,
        max_iters: int = 10,
        log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = "DEBUG",
    ):
        super().__init__()
        # Combine base tools with the generated tool
        self.tools = tools
        self.max_iters = max_iters
        self.agent = dspy.ReAct(
            signature=ToolAssessmentSignature,
            tools=self.tools,
            max_iters=self.max_iters,
        )
        self.log_level = log_level
        self.logger = get_logger(name="ToolAssessor", log_level=self.log_level)

    def forward(
        self,
        function_name: str,
        function_code: str,
        original_requirements: str,
        path_ifc_model: str,
    ) -> ModuleOutput:
        output = self.agent(
            function_name=function_name,
            function_code=function_code,
            original_requirements=original_requirements,
            test_file_path=path_ifc_model,
        )

        if output.assessment_status and output.assessment_details:
            self.logger.debug("Tool assessment successfull")
            self.logger.debug(f"Assessment status: \n{output.assessment_status}")
            self.logger.debug(f"Assessment details: \n{output.assessment_details}")
            return ModuleOutput(
                result=Result(
                    assessment_status=output.assessment_status,
                    assessment_details=output.assessment_details,
                ),
                status="success",
            )
        else:
            self.logger.debug("Tool assessment failed")
            return ModuleOutput(status="error", error_msg="Tool assessment failed")


# =============== Define ToolCorrector =============== #
class ToolCorrectionSignature(dspy.Signature):
    f"""
    Update a Python function implementation to incorporate the provided feedback.
    An assessment was conducted on the current implementation and has assessed that it is not working properly. Details regarding what needs to be changed are provided.

    The generated function should:
    - Take at least one argument: path_ifc_file: str, which is a path to the .ifc file the function should interact with.
    - Be well-documented with docstrings and type hints

    IMPORTANT:
    - Do not make assumptions about IFC schema or data structure.
    - Use the provided tools to research proper implementation details through documentation and web search.

    Below is an overview of how the structure of the IfcOpenShell Python library. For details regarding the implementation of each available method, use the `query_ifcopenshell_documentation` tool.

    Overview:
    {IFCOPENSHELL_DOCUMENTATION_OVERVIEW}
    """

    # inputs
    function_description: str = dspy.InputField(
        desc="Detailed description of what the function should do and its requirements."
    )

    function_name: str = dspy.InputField(desc="Name of the function.")

    current_function_implementation: str = dspy.InputField(
        desc="Current implementation of the function that needs to be updated."
    )

    detailed_function_assessment: str = dspy.InputField(
        desc="The detailed assessment of the current implementation of the function."
    )

    # outputs
    new_function_implementation: str = dspy.OutputField(
        desc="The updated implementation of the required function, mitigating the issues identified in the detailed assessment."
    )


class ToolCorrector(dspy.Module):
    """Module to correct an existing Python function."""

    def __init__(
        self,
        tools: list,
        max_iters: int = 10,
        log_level: Literal["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = "DEBUG",
    ):
        super().__init__()
        self.tools = tools
        self.max_iters = max_iters
        self.agent = dspy.ReAct(
            signature=ToolCorrectionSignature, tools=tools, max_iters=self.max_iters
        )
        self.log_level = log_level
        self.logger = get_logger(name="ToolCorrector", log_level=self.log_level)

    def forward(
        self,
        function_description: str,
        function_name: str,
        current_function_implementation: str,
        detailed_function_assessment: str,
    ) -> ModuleOutput:
        result = self.agent(
            function_description=function_description,
            function_name=function_name,
            current_function_implementation=current_function_implementation,
            detailed_function_assessment=detailed_function_assessment,
        )

        if result.new_function_implementation:
            self.logger.info("ToolCorrector updated the implementation successfully")
            self.logger.debug(
                f"New implementation: {result.new_function_implementation}"
            )
            return ModuleOutput(
                result=Result(python_code=result.new_function_implementation),
                status="success",
            )
        else:
            self.logger.info("ToolCorrector failed to update the function.")
            return ModuleOutput(
                status="error", error_msg="ToolCorrector failed to update the function."
            )


# =============== Additional Python Executor tool =============== #


# TODO consider moving this to special tools
def python_interpreter(
    python_code: str, max_tokens_logs: int = 2**12, max_tokens_output: int = 2**12
) -> str:
    """
    Execute Python code and return both the result and any printed output.

    Args:
        code: The Python code to execute as a string

    Returns:
        A formatted string containing both the print outputs and return value
    """

    additional_authorized_imports = [
        "ifcopenshell",
        "ifcopenshell.util.element",
        "ifcopenshell.util.shape",
        "ifcopenshell.util.placement",
        "ifcopenshell.util.geolocation",
        "ifcopenshell.util.system",
        "ifcopenshell.geom",
        "ifcopenshell.file",
        "ifcopenshell.entity_instance",
        "math",
        "numpy",
        "pandas",
    ]

    interpreter = LocalPythonExecutor(
        additional_authorized_imports=additional_authorized_imports
    )

    returned_value, logs, is_final = interpreter(code_action=python_code)

    def truncatenate_text(text: str, max_tokens: int) -> str:
        encoding = tiktoken.get_encoding("cl100k_base")  # GPT-4 encoding
        tokens = encoding.encode(text)

        if len(tokens) <= max_tokens:
            return text

        truncated_tokens = tokens[:max_tokens]
        truncated_text = encoding.decode(truncated_tokens)

        return f"{truncated_text}\n\n...output truncatenated after {max_tokens} tokens."

    # format the response to include both printed output and the return value
    result = ""
    if logs:
        result += f"## Print output:\n{truncatenate_text(logs, max_tokens=max_tokens_logs)}\n\n"

    result += f"## Return value:\n{truncatenate_text(returned_value, max_tokens=max_tokens_output)}"

    return result


# CONTINUE HERE
def create_new_tool(
    function_requirements: str,
    function_name: str,
    path_ifc_model: str,
    llm_info: LLM = LANGUAGE_MODELS["claude"],
    max_iter: int = 3,
    function_boilerplate: str = FUNCTION_BOILERPLATE,
):
    """
    Create a new tool using a multi-agent system with unbiased testing.

    The workflow:
    1. ToolCreator generates the function code
    2. A new function with the source code is created in this thread
    3. ToolAssessor tests it as a tool without seeing the code
    4. ToolCorrector fixes issues if needed
    5. Repeat until satisfactory or max iterations reached
    """
    lm = dspy.LM(model=llm_info.url, api_key=llm_info.api_key)
    dspy.configure(lm=lm)

    base_tools = [web_search, query_ifcopenshell_documentation, python_interpreter]
    tool_creator = ToolCreator(tools=base_tools)
    tool_corrector = ToolCorrector(tools=base_tools)

    current_iteration = 0

    logger.info(f"Starting the creation of the tool: {function_name}")

    # Step 1: Create initial function
    logger.info(
        f"\n--- Iteration {current_iteration + 1}: Creating initial function ---"
    )
    creation_result = tool_creator(
        function_description=function_requirements,
        function_name=function_name,
        function_boilerplate=function_boilerplate,
    )

    if creation_result.implementation_status == "error":
        error_msg = getattr(creation_result, "error_message", "Unknown error occurred")
        return {
            "status": "failed",
            "error": f"Tool creation failed: {error_msg}",
            "iterations": current_iteration + 1,
        }

    current_code = creation_result.python_code
    print("✓ Function created successfully")

    # Iterative improvement loop
    while current_iteration < max_iter:
        current_iteration += 1

        print(f"\n--- Iteration {current_iteration}: Testing function ---")

        # Step 2: Create enhanced assessor with dynamic tool
        try:
            enhanced_assessor = create_assessor_with_dynamic_tool(
                base_tools=base_tools,
                generated_code=current_code,
                function_name=function_name,
            )
            print("✓ Enhanced assessor created with dynamic tool")
        except Exception as e:
            print(f"✗ Failed to create enhanced assessor: {str(e)}")
            break

        # Step 3: Assess the function
        try:
            assessment_result = enhanced_assessor(
                function_name=function_name,
                function_requirements=function_requirements,
                path_ifc_model=path_ifc_model,
            )
            print(f"✓ Assessment completed: {assessment_result.assessment_status}")
            print(f"Assessment details: {assessment_result.assessment_details}")
        except Exception as e:
            print(f"✗ Assessment failed: {str(e)}")
            break

        # Step 4: Check if function is satisfactory
        if assessment_result.assessment_status == "ok":
            print(
                f"🎉 Function passed assessment after {current_iteration} iterations!"
            )
            return {
                "status": "success",
                "function_code": current_code,
                "function_name": function_name,
                "assessment_details": assessment_result.assessment_details,
                "iterations": current_iteration,
            }

        # Step 5: If not satisfactory and we have iterations left, correct the function
        if current_iteration < max_iter:
            print(f"\n--- Iteration {current_iteration}: Correcting function ---")
            correction_result = tool_corrector(
                function_description=function_requirements,
                function_name=function_name,
                current_function_implementation=current_code,
                detailed_function_assessment=assessment_result.assessment_details,
            )

            if correction_result.implementation_status == "error":
                print(
                    f"✗ Correction failed: {correction_result.new_function_implementation}"
                )
                break

            current_code = correction_result.new_function_implementation
            print("✓ Function corrected")
        else:
            print("⚠️  Maximum iterations reached")

    # Return final result even if not perfect
    return {
        "status": "partial_success" if current_iteration >= max_iter else "failed",
        "function_code": current_code,
        "function_name": function_name,
        "final_assessment": assessment_result.assessment_details
        if "assessment_result" in locals()
        else "Assessment not completed",
        "iterations": current_iteration,
        "note": "Function may need manual review"
        if current_iteration >= max_iter
        else "Process failed before completion",
    }


# %% Example Usage
# =============== Example Usage =============== #


def example_usage():
    """
    Example demonstrating how to use the multi-agent tool creation system.
    """
    # Define requirements for a new tool
    requirements = """
    Create a function that extracts all wall elements from an IFC file and returns
    their basic properties including name, type, height, and thickness. The function
    should handle cases where some properties might be missing and return the results
    as a JSON string for easy parsing.
    """

    # Path to an IFC file for testing
    path_ifc_model = (
        "/Users/sylvainhellin/GitHub/ifcAnswerEngineV3/src/bim_models/duplex/arc.ifc"
    )

    print(f"Creating tool with requirements: {requirements.strip()}")
    print(f"Using test IFC file: {path_ifc_model}")
    print(
        "\nNote: Make sure to update 'path_ifc_model' with a valid IFC file path before running."
    )

    # Create the tool
    result = create_new_tool(
        function_requirements=requirements, path_ifc_model=path_ifc_model
    )

    print("\nTool Creation Result:")
    print(f"Status: {result['status']}")
    print(f"Iterations: {result['iterations']}")

    if result["status"] == "success":
        print("✅ Tool created successfully!")
        print(f"Function name: {result['function_name']}")
        print("\nGenerated code:")
        print("=" * 50)
        print(result["function_code"])
        print("=" * 50)
    else:
        print("❌ Tool creation failed or needs improvement")
        if "error" in result:
            print(f"Error: {result['error']}")
        if "note" in result:
            print(f"Note: {result['note']}")
        if "function_code" in result:
            print("\nPartial implementation:")
            print("=" * 50)
            print(result["function_code"])
            print("=" * 50)


if __name__ == "__main__":
    example_usage()
