# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Cobbie(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.FinalAnswer"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="Cobbie", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.FinalAnswer"], result)

    def EvaluateResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnswerEvaluationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.AnswerEvaluationResult, result)

    def FaultyNewToolAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FaultyToolAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FaultyNewToolAnalysis", llm_response=llm_response, mode="request")
        return typing.cast(types.FaultyToolAnalysis, result)

    def HelperFunctionAssessor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.HelperFunctionAssessment:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionAssessor", llm_response=llm_response, mode="request")
        return typing.cast(types.HelperFunctionAssessment, result)

    def HelperFunctionCreator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.NewHelperFunction"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionCreator", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.NewHelperFunction"], result)

    def HelperFunctionDebugger(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.UpdatedHelperFunction"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionDebugger", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.UpdatedHelperFunction"], result)

    def HelperFunctionIdentifier(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NewToolAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionIdentifier", llm_response=llm_response, mode="request")
        return typing.cast(types.NewToolAnalysis, result)

    def QuestionAnswerAlignment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AlignedQAPair:
        result = self.__options.merge_options(baml_options).parse_response(function_name="QuestionAnswerAlignment", llm_response=llm_response, mode="request")
        return typing.cast(types.AlignedQAPair, result)

    def ValidateQuestionCategory(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CategoryValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateQuestionCategory", llm_response=llm_response, mode="request")
        return typing.cast(types.CategoryValidationResult, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Cobbie(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="Cobbie", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"], result)

    def EvaluateResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnswerEvaluationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnswerEvaluationResult, result)

    def FaultyNewToolAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FaultyToolAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="FaultyNewToolAnalysis", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FaultyToolAnalysis, result)

    def HelperFunctionAssessor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.HelperFunctionAssessment:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionAssessor", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.HelperFunctionAssessment, result)

    def HelperFunctionCreator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionCreator", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], result)

    def HelperFunctionDebugger(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.UpdatedHelperFunction"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionDebugger", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.UpdatedHelperFunction"], result)

    def HelperFunctionIdentifier(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NewToolAnalysis:
        result = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionIdentifier", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NewToolAnalysis, result)

    def QuestionAnswerAlignment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AlignedQAPair:
        result = self.__options.merge_options(baml_options).parse_response(function_name="QuestionAnswerAlignment", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AlignedQAPair, result)

    def ValidateQuestionCategory(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CategoryValidationResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateQuestionCategory", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CategoryValidationResult, result)

    