# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BIMQAS(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.FinalAnswer"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="BIMQAS", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.FinalAnswer"], result)

    def CodeExtractor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FunctionImplementation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CodeExtractor", llm_response=llm_response, mode="request")
        return typing.cast(types.FunctionImplementation, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def ToolCreator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.FunctionImplementation"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ToolCreator", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.FunctionImplementation"], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BIMQAS(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="BIMQAS", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"], result)

    def CodeExtractor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FunctionImplementation:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CodeExtractor", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FunctionImplementation, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def ToolCreator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.FunctionImplementation"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ToolCreator", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.FunctionImplementation"], result)

    