# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ACCToolAssessor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ACCToolAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ACCToolAssessor", llm_response=llm_response, mode="request")
        return typing.cast(types.ACCToolAssessment, __result__)

    def Cobbie(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.FinalAnswer"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Cobbie", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.FinalAnswer"], __result__)

    def EvaluateResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AnswerEvaluationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.AnswerEvaluationResult, __result__)

    def FaultyNewToolAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FaultyToolAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FaultyNewToolAnalysis", llm_response=llm_response, mode="request")
        return typing.cast(types.FaultyToolAnalysis, __result__)

    def HelperFunctionAssessor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.HelperFunctionAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionAssessor", llm_response=llm_response, mode="request")
        return typing.cast(types.HelperFunctionAssessment, __result__)

    def HelperFunctionCreator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.NewHelperFunction"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionCreator", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.NewHelperFunction"], __result__)

    def HelperFunctionDebugger(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.UpdatedHelperFunction"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionDebugger", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.CodeAction", "types.UpdatedHelperFunction"], __result__)

    def HelperFunctionIdentifier(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NewToolAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionIdentifier", llm_response=llm_response, mode="request")
        return typing.cast(types.NewToolAnalysis, __result__)

    def QuestionAnswerAlignment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AlignedQAPair:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="QuestionAnswerAlignment", llm_response=llm_response, mode="request")
        return typing.cast(types.AlignedQAPair, __result__)

    def ValidateQuestionCategory(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CategoryValidationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ValidateQuestionCategory", llm_response=llm_response, mode="request")
        return typing.cast(types.CategoryValidationResult, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ACCToolAssessor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ACCToolAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ACCToolAssessor", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ACCToolAssessment, __result__)

    def Cobbie(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Cobbie", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"], __result__)

    def EvaluateResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AnswerEvaluationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AnswerEvaluationResult, __result__)

    def FaultyNewToolAnalysis(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FaultyToolAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="FaultyNewToolAnalysis", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FaultyToolAnalysis, __result__)

    def HelperFunctionAssessor(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.HelperFunctionAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionAssessor", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.HelperFunctionAssessment, __result__)

    def HelperFunctionCreator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionCreator", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], __result__)

    def HelperFunctionDebugger(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.CodeAction", "stream_types.UpdatedHelperFunction"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionDebugger", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.CodeAction", "stream_types.UpdatedHelperFunction"], __result__)

    def HelperFunctionIdentifier(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NewToolAnalysis:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="HelperFunctionIdentifier", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NewToolAnalysis, __result__)

    def QuestionAnswerAlignment(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AlignedQAPair:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="QuestionAnswerAlignment", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AlignedQAPair, __result__)

    def ValidateQuestionCategory(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CategoryValidationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ValidateQuestionCategory", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CategoryValidationResult, __result__)

    