# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (15)
# #########################################################################

class AlignedQAPair(BaseModel):
    thought: typing.Optional[str] = None
    aligned_question: typing.Optional[str] = None
    aligned_answer: typing.Optional[str] = None
    was_modified: typing.Optional[bool] = None

class AnswerEvaluationResult(BaseModel):
    classification: typing.Optional[typing.Union[str, str, str]] = None
    justification: typing.Optional[str] = None
    confidence: typing.Optional[typing.Union[str, str, str]] = None

class AssessmentResult(BaseModel):
    assessment_status: typing.Optional[typing.Union[str, str]] = None
    assessment_details: typing.Optional[str] = None
    test_execution_log: typing.Optional[str] = None

class CategoryValidationResult(BaseModel):
    validated_category: typing.Optional[str] = None
    updated: typing.Optional[bool] = None
    thought: typing.Optional[str] = None

class CleanedCode(BaseModel):
    function_implementation: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None
    success: typing.Optional[bool] = None

class CodeAction(BaseModel):
    thoughts: typing.Optional[str] = None
    python_code: typing.Optional[str] = None

class ErrorAnalysisResult(BaseModel):
    error_category: typing.Optional[str] = None
    function_name: typing.Optional[str] = None
    needs_new_tool: typing.Optional[bool] = None

class FinalAnswer(BaseModel):
    thoughts: typing.Optional[str] = None
    answer: typing.Optional[str] = None

class FunctionImplementation(BaseModel):
    function_implementation: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    needs_improvement: typing.Optional[bool] = None

class ImprovedImplementation(BaseModel):
    function_implementation: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None
    changes_summary: typing.Optional[str] = None

class SimilarityResult(BaseModel):
    similarity_score: typing.Optional[float] = None
    correct_answer: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None

class TestAndImproveError(BaseModel):
    error_message: typing.Optional[str] = None
    iterations_completed: typing.Optional[int] = None
    final_assessment_status: typing.Optional[str] = None
    partial_function_implementation: typing.Optional[str] = None

class TestAndImproveSuccess(BaseModel):
    function_implementation: typing.Optional[str] = None
    assessment_details: typing.Optional[str] = None
    iterations_used: typing.Optional[int] = None
    total_time_seconds: typing.Optional[float] = None

class ToolCreationResult(BaseModel):
    function_name: typing.Optional[str] = None
    function_implementation: typing.Optional[str] = None
    success: typing.Optional[bool] = None

class ToolOptimizationResult(BaseModel):
    improvement: typing.Optional[str] = None
    function_name: typing.Optional[str] = None
    function_requirements: typing.Optional[str] = None
    existing_tool_names: typing.Optional[typing.List[str]] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
