# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (21)
# #########################################################################

class AlignedQAPair(BaseModel):
    thought: typing.Optional[str] = None
    aligned_question: typing.Optional[str] = None
    aligned_answer: typing.Optional[str] = None
    was_modified: typing.Optional[bool] = None

class AnswerEvaluationResult(BaseModel):
    abstention: typing.Optional[bool] = None
    faithfulness: typing.Optional[types.CriterionResult] = None
    completeness: typing.Optional[types.CriterionResult] = None
    transparency: typing.Optional[types.CriterionResult] = None
    relevance: typing.Optional[types.CriterionResult] = None
    justification: typing.Optional[str] = None

class AssessmentResult(BaseModel):
    assessment_status: typing.Optional[typing.Union[typing_extensions.Literal['ok'], typing_extensions.Literal['needs_improvement']]] = None
    assessment_details: typing.Optional[str] = None
    test_execution_log: typing.Optional[str] = None

class CategoryValidationResult(BaseModel):
    validated_category: typing.Optional[str] = None
    updated: typing.Optional[bool] = None
    thought: typing.Optional[str] = None

class ChunkReviewInput(BaseModel):
    chunk_type: typing.Optional[str] = None
    name: typing.Optional[str] = None
    module_path: typing.Optional[str] = None
    signature: typing.Optional[str] = None
    content: typing.Optional[str] = None

class ChunkReviewOutput(BaseModel):
    useful: typing.Optional[bool] = None
    reason: typing.Optional[str] = None
    questions: typing.List[str]

class CodeAction(BaseModel):
    thoughts: typing.Optional[str] = None
    python_code: typing.Optional[str] = None

class ErrorAnalysisResult(BaseModel):
    error_category: typing.Optional[str] = None
    function_name: typing.Optional[str] = None
    needs_new_tool: typing.Optional[bool] = None

class FaultyToolAnalysis(BaseModel):
    thoughts: typing.Optional[str] = None
    faulty_tool: typing.Optional[bool] = None
    faulty_tool_name: typing.Optional[str] = None
    error_description: typing.Optional[str] = None
    confidence: typing.Optional[typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]] = None

class FinalAnswer(BaseModel):
    thoughts: typing.Optional[str] = None
    answer: typing.Optional[str] = None

class FunctionImplementation(BaseModel):
    function_implementation: typing.Optional[str] = None
    confidence: typing.Optional[float] = None
    needs_improvement: typing.Optional[bool] = None

class HelperFunctionAssessment(BaseModel):
    thoughts: typing.Optional[str] = None
    tool_was_used: typing.Optional[bool] = None
    tool_usage_quality: typing.Optional[typing.Union[typing_extensions.Literal['helpful'], typing_extensions.Literal['not_used'], typing_extensions.Literal['ignored'], typing_extensions.Literal['misused'], typing_extensions.Literal['harmful']]] = None
    usage_details: typing.Optional[str] = None
    recommendation: typing.Optional[typing.Union[typing_extensions.Literal['keep_tool'], typing_extensions.Literal['discard_tool'], typing_extensions.Literal['improve_tool'], typing_extensions.Literal['unclear']]] = None
    confidence: typing.Optional[typing.Union[typing_extensions.Literal['high'], typing_extensions.Literal['medium'], typing_extensions.Literal['low']]] = None

class ImprovedImplementation(BaseModel):
    function_implementation: typing.Optional[str] = None
    reasoning: typing.Optional[str] = None
    changes_summary: typing.Optional[str] = None

class NewHelperFunction(BaseModel):
    thoughts: typing.Optional[str] = None
    function_implementation: typing.Optional[str] = None
    success: typing.Optional[bool] = None

class NewToolAnalysis(BaseModel):
    thoughts: typing.Optional[str] = None
    action: typing.Optional[typing.Union[typing_extensions.Literal['create_new'], typing_extensions.Literal['enhance_existing'], typing_extensions.Literal['none']]] = None
    tool_name: typing.Optional[str] = None
    tool_description: typing.Optional[str] = None
    existing_tool_for_enhancement: typing.Optional[str] = None

class SimilarityResult(BaseModel):
    similarity_score: typing.Optional[float] = None
    correct_answer: typing.Optional[bool] = None
    reasoning: typing.Optional[str] = None

class TestAndImproveError(BaseModel):
    error_message: typing.Optional[str] = None
    iterations_completed: typing.Optional[int] = None
    final_assessment_status: typing.Optional[str] = None
    partial_function_implementation: typing.Optional[str] = None

class TestAndImproveSuccess(BaseModel):
    function_implementation: typing.Optional[str] = None
    assessment_details: typing.Optional[str] = None
    iterations_used: typing.Optional[int] = None
    total_time_seconds: typing.Optional[float] = None

class ToolCreationResult(BaseModel):
    function_name: typing.Optional[str] = None
    function_implementation: typing.Optional[str] = None
    success: typing.Optional[bool] = None

class ToolOptimizationResult(BaseModel):
    improvement: typing.Optional[str] = None
    function_name: typing.Optional[str] = None
    function_requirements: typing.Optional[str] = None
    existing_tool_names: typing.Optional[typing.List[str]] = None

class UpdatedHelperFunction(BaseModel):
    thoughts: typing.Optional[str] = None
    fixed_implementation: typing.Optional[str] = None
    changes_summary: typing.Optional[str] = None
    success: typing.Optional[bool] = None
    test_cases_provided: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
