# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def Cobbie(self, user_input: str,available_tools: str,previous_attempts: typing.Optional[str] = None,model_path: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.FinalAnswer"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.Cobbie(user_input=user_input,available_tools=available_tools,previous_attempts=previous_attempts,model_path=model_path,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="Cobbie", args={
                "user_input": user_input,"available_tools": available_tools,"previous_attempts": previous_attempts,"model_path": model_path,
            })
            return typing.cast(typing.Union["types.CodeAction", "types.FinalAnswer"], result.cast_to(types, types, stream_types, False, __runtime__))
    def EvaluateResponse(self, question: str,category: types.QuestionCategory,ground_truth: str,system_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AnswerEvaluationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.EvaluateResponse(question=question,category=category,ground_truth=ground_truth,system_response=system_response,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="EvaluateResponse", args={
                "question": question,"category": category,"ground_truth": ground_truth,"system_response": system_response,
            })
            return typing.cast(types.AnswerEvaluationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def FaultyNewToolAnalysis(self, history: str,question: str,ground_truth: str,provided_answer: str,justification: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> types.FaultyToolAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.FaultyNewToolAnalysis(history=history,question=question,ground_truth=ground_truth,provided_answer=provided_answer,justification=justification,existing_helper_functions=existing_helper_functions,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="FaultyNewToolAnalysis", args={
                "history": history,"question": question,"ground_truth": ground_truth,"provided_answer": provided_answer,"justification": justification,"existing_helper_functions": existing_helper_functions,
            })
            return typing.cast(types.FaultyToolAnalysis, result.cast_to(types, types, stream_types, False, __runtime__))
    def HelperFunctionAssessor(self, execution_history: str,original_question: str,ground_truth_answer: str,tested_tool_name: str,tested_tool_description: str,final_answer: str,answer_correctness: typing.Union[typing_extensions.Literal['correct'], typing_extensions.Literal['wrong'], typing_extensions.Literal['abstained']],
        baml_options: BamlCallOptions = {},
    ) -> types.HelperFunctionAssessment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.HelperFunctionAssessor(execution_history=execution_history,original_question=original_question,ground_truth_answer=ground_truth_answer,tested_tool_name=tested_tool_name,tested_tool_description=tested_tool_description,final_answer=final_answer,answer_correctness=answer_correctness,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="HelperFunctionAssessor", args={
                "execution_history": execution_history,"original_question": original_question,"ground_truth_answer": ground_truth_answer,"tested_tool_name": tested_tool_name,"tested_tool_description": tested_tool_description,"final_answer": final_answer,"answer_correctness": answer_correctness,
            })
            return typing.cast(types.HelperFunctionAssessment, result.cast_to(types, types, stream_types, False, __runtime__))
    def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.NewHelperFunction"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.HelperFunctionCreator(history=history,example_question=example_question,example_answer=example_answer,example_bim_model=example_bim_model,other_bim_models_for_testing=other_bim_models_for_testing,function_name=function_name,function_description=function_description,is_enhancement=is_enhancement,existing_implementation=existing_implementation,previous_attempts=previous_attempts,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="HelperFunctionCreator", args={
                "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,
            })
            return typing.cast(typing.Union["types.CodeAction", "types.NewHelperFunction"], result.cast_to(types, types, stream_types, False, __runtime__))
    def HelperFunctionDebugger(self, faulty_function_name: str,faulty_function_implementation: str,history_faulty_tool_use: typing.Optional[str],error_description: str,ifc_model_path: str,other_bim_models_for_testing: typing.Optional[typing.List[str]] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.CodeAction", "types.UpdatedHelperFunction"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.HelperFunctionDebugger(faulty_function_name=faulty_function_name,faulty_function_implementation=faulty_function_implementation,history_faulty_tool_use=history_faulty_tool_use,error_description=error_description,ifc_model_path=ifc_model_path,other_bim_models_for_testing=other_bim_models_for_testing,previous_attempts=previous_attempts,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="HelperFunctionDebugger", args={
                "faulty_function_name": faulty_function_name,"faulty_function_implementation": faulty_function_implementation,"history_faulty_tool_use": history_faulty_tool_use,"error_description": error_description,"ifc_model_path": ifc_model_path,"other_bim_models_for_testing": other_bim_models_for_testing,"previous_attempts": previous_attempts,
            })
            return typing.cast(typing.Union["types.CodeAction", "types.UpdatedHelperFunction"], result.cast_to(types, types, stream_types, False, __runtime__))
    def HelperFunctionIdentifier(self, history: str,example_question: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> types.NewToolAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.HelperFunctionIdentifier(history=history,example_question=example_question,existing_helper_functions=existing_helper_functions,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="HelperFunctionIdentifier", args={
                "history": history,"example_question": example_question,"existing_helper_functions": existing_helper_functions,
            })
            return typing.cast(types.NewToolAnalysis, result.cast_to(types, types, stream_types, False, __runtime__))
    def QuestionAnswerAlignment(self, question: str,answer: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AlignedQAPair:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.QuestionAnswerAlignment(question=question,answer=answer,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="QuestionAnswerAlignment", args={
                "question": question,"answer": answer,
            })
            return typing.cast(types.AlignedQAPair, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidateQuestionCategory(self, question: str,answer: str,current_category: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CategoryValidationResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidateQuestionCategory(question=question,answer=answer,current_category=current_category,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidateQuestionCategory", args={
                "question": question,"answer": answer,"current_category": current_category,
            })
            return typing.cast(types.CategoryValidationResult, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Cobbie(self, user_input: str,available_tools: str,previous_attempts: typing.Optional[str] = None,model_path: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"], typing.Union["types.CodeAction", "types.FinalAnswer"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="Cobbie", args={
            "user_input": user_input,"available_tools": available_tools,"previous_attempts": previous_attempts,"model_path": model_path,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"], typing.Union["types.CodeAction", "types.FinalAnswer"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.CodeAction", "stream_types.FinalAnswer"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.CodeAction", "types.FinalAnswer"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def EvaluateResponse(self, question: str,category: types.QuestionCategory,ground_truth: str,system_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AnswerEvaluationResult, types.AnswerEvaluationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="EvaluateResponse", args={
            "question": question,"category": category,"ground_truth": ground_truth,"system_response": system_response,
        })
        return baml_py.BamlSyncStream[stream_types.AnswerEvaluationResult, types.AnswerEvaluationResult](
          result,
          lambda x: typing.cast(stream_types.AnswerEvaluationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AnswerEvaluationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def FaultyNewToolAnalysis(self, history: str,question: str,ground_truth: str,provided_answer: str,justification: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FaultyToolAnalysis, types.FaultyToolAnalysis]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="FaultyNewToolAnalysis", args={
            "history": history,"question": question,"ground_truth": ground_truth,"provided_answer": provided_answer,"justification": justification,"existing_helper_functions": existing_helper_functions,
        })
        return baml_py.BamlSyncStream[stream_types.FaultyToolAnalysis, types.FaultyToolAnalysis](
          result,
          lambda x: typing.cast(stream_types.FaultyToolAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FaultyToolAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def HelperFunctionAssessor(self, execution_history: str,original_question: str,ground_truth_answer: str,tested_tool_name: str,tested_tool_description: str,final_answer: str,answer_correctness: typing.Union[typing_extensions.Literal['correct'], typing_extensions.Literal['wrong'], typing_extensions.Literal['abstained']],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.HelperFunctionAssessment, types.HelperFunctionAssessment]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="HelperFunctionAssessor", args={
            "execution_history": execution_history,"original_question": original_question,"ground_truth_answer": ground_truth_answer,"tested_tool_name": tested_tool_name,"tested_tool_description": tested_tool_description,"final_answer": final_answer,"answer_correctness": answer_correctness,
        })
        return baml_py.BamlSyncStream[stream_types.HelperFunctionAssessment, types.HelperFunctionAssessment](
          result,
          lambda x: typing.cast(stream_types.HelperFunctionAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.HelperFunctionAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], typing.Union["types.CodeAction", "types.NewHelperFunction"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="HelperFunctionCreator", args={
            "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], typing.Union["types.CodeAction", "types.NewHelperFunction"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.CodeAction", "stream_types.NewHelperFunction"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.CodeAction", "types.NewHelperFunction"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def HelperFunctionDebugger(self, faulty_function_name: str,faulty_function_implementation: str,history_faulty_tool_use: typing.Optional[str],error_description: str,ifc_model_path: str,other_bim_models_for_testing: typing.Optional[typing.List[str]] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.CodeAction", "stream_types.UpdatedHelperFunction"], typing.Union["types.CodeAction", "types.UpdatedHelperFunction"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="HelperFunctionDebugger", args={
            "faulty_function_name": faulty_function_name,"faulty_function_implementation": faulty_function_implementation,"history_faulty_tool_use": history_faulty_tool_use,"error_description": error_description,"ifc_model_path": ifc_model_path,"other_bim_models_for_testing": other_bim_models_for_testing,"previous_attempts": previous_attempts,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.CodeAction", "stream_types.UpdatedHelperFunction"], typing.Union["types.CodeAction", "types.UpdatedHelperFunction"]](
          result,
          lambda x: typing.cast(typing.Union["stream_types.CodeAction", "stream_types.UpdatedHelperFunction"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.CodeAction", "types.UpdatedHelperFunction"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def HelperFunctionIdentifier(self, history: str,example_question: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NewToolAnalysis, types.NewToolAnalysis]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="HelperFunctionIdentifier", args={
            "history": history,"example_question": example_question,"existing_helper_functions": existing_helper_functions,
        })
        return baml_py.BamlSyncStream[stream_types.NewToolAnalysis, types.NewToolAnalysis](
          result,
          lambda x: typing.cast(stream_types.NewToolAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NewToolAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def QuestionAnswerAlignment(self, question: str,answer: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AlignedQAPair, types.AlignedQAPair]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="QuestionAnswerAlignment", args={
            "question": question,"answer": answer,
        })
        return baml_py.BamlSyncStream[stream_types.AlignedQAPair, types.AlignedQAPair](
          result,
          lambda x: typing.cast(stream_types.AlignedQAPair, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AlignedQAPair, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidateQuestionCategory(self, question: str,answer: str,current_category: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CategoryValidationResult, types.CategoryValidationResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidateQuestionCategory", args={
            "question": question,"answer": answer,"current_category": current_category,
        })
        return baml_py.BamlSyncStream[stream_types.CategoryValidationResult, types.CategoryValidationResult](
          result,
          lambda x: typing.cast(stream_types.CategoryValidationResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CategoryValidationResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Cobbie(self, user_input: str,available_tools: str,previous_attempts: typing.Optional[str] = None,model_path: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Cobbie", args={
            "user_input": user_input,"available_tools": available_tools,"previous_attempts": previous_attempts,"model_path": model_path,
        }, mode="request")
        return result
    def EvaluateResponse(self, question: str,category: types.QuestionCategory,ground_truth: str,system_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluateResponse", args={
            "question": question,"category": category,"ground_truth": ground_truth,"system_response": system_response,
        }, mode="request")
        return result
    def FaultyNewToolAnalysis(self, history: str,question: str,ground_truth: str,provided_answer: str,justification: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FaultyNewToolAnalysis", args={
            "history": history,"question": question,"ground_truth": ground_truth,"provided_answer": provided_answer,"justification": justification,"existing_helper_functions": existing_helper_functions,
        }, mode="request")
        return result
    def HelperFunctionAssessor(self, execution_history: str,original_question: str,ground_truth_answer: str,tested_tool_name: str,tested_tool_description: str,final_answer: str,answer_correctness: typing.Union[typing_extensions.Literal['correct'], typing_extensions.Literal['wrong'], typing_extensions.Literal['abstained']],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionAssessor", args={
            "execution_history": execution_history,"original_question": original_question,"ground_truth_answer": ground_truth_answer,"tested_tool_name": tested_tool_name,"tested_tool_description": tested_tool_description,"final_answer": final_answer,"answer_correctness": answer_correctness,
        }, mode="request")
        return result
    def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionCreator", args={
            "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,
        }, mode="request")
        return result
    def HelperFunctionDebugger(self, faulty_function_name: str,faulty_function_implementation: str,history_faulty_tool_use: typing.Optional[str],error_description: str,ifc_model_path: str,other_bim_models_for_testing: typing.Optional[typing.List[str]] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionDebugger", args={
            "faulty_function_name": faulty_function_name,"faulty_function_implementation": faulty_function_implementation,"history_faulty_tool_use": history_faulty_tool_use,"error_description": error_description,"ifc_model_path": ifc_model_path,"other_bim_models_for_testing": other_bim_models_for_testing,"previous_attempts": previous_attempts,
        }, mode="request")
        return result
    def HelperFunctionIdentifier(self, history: str,example_question: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionIdentifier", args={
            "history": history,"example_question": example_question,"existing_helper_functions": existing_helper_functions,
        }, mode="request")
        return result
    def QuestionAnswerAlignment(self, question: str,answer: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="QuestionAnswerAlignment", args={
            "question": question,"answer": answer,
        }, mode="request")
        return result
    def ValidateQuestionCategory(self, question: str,answer: str,current_category: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateQuestionCategory", args={
            "question": question,"answer": answer,"current_category": current_category,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def Cobbie(self, user_input: str,available_tools: str,previous_attempts: typing.Optional[str] = None,model_path: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="Cobbie", args={
            "user_input": user_input,"available_tools": available_tools,"previous_attempts": previous_attempts,"model_path": model_path,
        }, mode="stream")
        return result
    def EvaluateResponse(self, question: str,category: types.QuestionCategory,ground_truth: str,system_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="EvaluateResponse", args={
            "question": question,"category": category,"ground_truth": ground_truth,"system_response": system_response,
        }, mode="stream")
        return result
    def FaultyNewToolAnalysis(self, history: str,question: str,ground_truth: str,provided_answer: str,justification: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="FaultyNewToolAnalysis", args={
            "history": history,"question": question,"ground_truth": ground_truth,"provided_answer": provided_answer,"justification": justification,"existing_helper_functions": existing_helper_functions,
        }, mode="stream")
        return result
    def HelperFunctionAssessor(self, execution_history: str,original_question: str,ground_truth_answer: str,tested_tool_name: str,tested_tool_description: str,final_answer: str,answer_correctness: typing.Union[typing_extensions.Literal['correct'], typing_extensions.Literal['wrong'], typing_extensions.Literal['abstained']],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionAssessor", args={
            "execution_history": execution_history,"original_question": original_question,"ground_truth_answer": ground_truth_answer,"tested_tool_name": tested_tool_name,"tested_tool_description": tested_tool_description,"final_answer": final_answer,"answer_correctness": answer_correctness,
        }, mode="stream")
        return result
    def HelperFunctionCreator(self, history: str,example_question: str,example_answer: str,example_bim_model: str,other_bim_models_for_testing: typing.Optional[typing.List[str]],function_name: str,function_description: str,is_enhancement: bool,existing_implementation: typing.Optional[str] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionCreator", args={
            "history": history,"example_question": example_question,"example_answer": example_answer,"example_bim_model": example_bim_model,"other_bim_models_for_testing": other_bim_models_for_testing,"function_name": function_name,"function_description": function_description,"is_enhancement": is_enhancement,"existing_implementation": existing_implementation,"previous_attempts": previous_attempts,
        }, mode="stream")
        return result
    def HelperFunctionDebugger(self, faulty_function_name: str,faulty_function_implementation: str,history_faulty_tool_use: typing.Optional[str],error_description: str,ifc_model_path: str,other_bim_models_for_testing: typing.Optional[typing.List[str]] = None,previous_attempts: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionDebugger", args={
            "faulty_function_name": faulty_function_name,"faulty_function_implementation": faulty_function_implementation,"history_faulty_tool_use": history_faulty_tool_use,"error_description": error_description,"ifc_model_path": ifc_model_path,"other_bim_models_for_testing": other_bim_models_for_testing,"previous_attempts": previous_attempts,
        }, mode="stream")
        return result
    def HelperFunctionIdentifier(self, history: str,example_question: str,existing_helper_functions: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="HelperFunctionIdentifier", args={
            "history": history,"example_question": example_question,"existing_helper_functions": existing_helper_functions,
        }, mode="stream")
        return result
    def QuestionAnswerAlignment(self, question: str,answer: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="QuestionAnswerAlignment", args={
            "question": question,"answer": answer,
        }, mode="stream")
        return result
    def ValidateQuestionCategory(self, question: str,answer: str,current_category: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateQuestionCategory", args={
            "question": question,"answer": answer,"current_category": current_category,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))