# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (13)
# #########################################################################

class AssessmentResult(BaseModel):
    assessment_status: str
    assessment_details: str
    test_execution_log: typing.Optional[str] = None

class CleanedCode(BaseModel):
    function_implementation: str
    reasoning: str
    success: bool

class CodeAction(BaseModel):
    thoughts: str
    python_code: str

class ErrorAnalysisResult(BaseModel):
    error_category: str
    function_name: typing.Optional[str] = None
    needs_new_tool: bool

class FinalAnswer(BaseModel):
    thoughts: str
    answer: str

class FunctionImplementation(BaseModel):
    function_implementation: str
    confidence: typing.Optional[float] = None
    needs_improvement: bool

class ImprovedImplementation(BaseModel):
    function_implementation: str
    reasoning: str
    changes_summary: typing.Optional[str] = None

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class SimilarityResult(BaseModel):
    similarity_score: float
    correct_answer: bool
    reasoning: str

class TestAndImproveError(BaseModel):
    error_message: str
    iterations_completed: int
    final_assessment_status: typing.Optional[str] = None
    partial_function_implementation: typing.Optional[str] = None

class TestAndImproveSuccess(BaseModel):
    function_implementation: str
    assessment_details: str
    iterations_used: int
    total_time_seconds: float

class ToolCreationResult(BaseModel):
    function_name: str
    function_implementation: str
    success: bool

class ToolOptimizationResult(BaseModel):
    improvement: str
    function_name: typing.Optional[str] = None
    function_requirements: typing.Optional[str] = None
    existing_tool_names: typing.Optional[typing.List[str]] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
