# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AssessmentResult": types.AssessmentResult,
    "stream_types.AssessmentResult": stream_types.AssessmentResult,

    "types.CleanedCode": types.CleanedCode,
    "stream_types.CleanedCode": stream_types.CleanedCode,

    "types.CodeAction": types.CodeAction,
    "stream_types.CodeAction": stream_types.CodeAction,

    "types.ErrorAnalysisResult": types.ErrorAnalysisResult,
    "stream_types.ErrorAnalysisResult": stream_types.ErrorAnalysisResult,

    "types.FinalAnswer": types.FinalAnswer,
    "stream_types.FinalAnswer": stream_types.FinalAnswer,

    "types.FunctionImplementation": types.FunctionImplementation,
    "stream_types.FunctionImplementation": stream_types.FunctionImplementation,

    "types.ImprovedImplementation": types.ImprovedImplementation,
    "stream_types.ImprovedImplementation": stream_types.ImprovedImplementation,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.SimilarityResult": types.SimilarityResult,
    "stream_types.SimilarityResult": stream_types.SimilarityResult,

    "types.ToolCreationResult": types.ToolCreationResult,
    "stream_types.ToolCreationResult": stream_types.ToolCreationResult,

    "types.ToolOptimizationResult": types.ToolOptimizationResult,
    "stream_types.ToolOptimizationResult": stream_types.ToolOptimizationResult,


}