# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.AlignedQAPair": types.AlignedQAPair,
    "stream_types.AlignedQAPair": stream_types.AlignedQAPair,

    "types.AnswerEvaluationResult": types.AnswerEvaluationResult,
    "stream_types.AnswerEvaluationResult": stream_types.AnswerEvaluationResult,

    "types.AssessmentResult": types.AssessmentResult,
    "stream_types.AssessmentResult": stream_types.AssessmentResult,

    "types.CategoryValidationResult": types.CategoryValidationResult,
    "stream_types.CategoryValidationResult": stream_types.CategoryValidationResult,

    "types.CodeAction": types.CodeAction,
    "stream_types.CodeAction": stream_types.CodeAction,

    "types.ErrorAnalysisResult": types.ErrorAnalysisResult,
    "stream_types.ErrorAnalysisResult": stream_types.ErrorAnalysisResult,

    "types.FaultyToolAnalysis": types.FaultyToolAnalysis,
    "stream_types.FaultyToolAnalysis": stream_types.FaultyToolAnalysis,

    "types.FinalAnswer": types.FinalAnswer,
    "stream_types.FinalAnswer": stream_types.FinalAnswer,

    "types.FunctionImplementation": types.FunctionImplementation,
    "stream_types.FunctionImplementation": stream_types.FunctionImplementation,

    "types.HelperFunctionAssessment": types.HelperFunctionAssessment,
    "stream_types.HelperFunctionAssessment": stream_types.HelperFunctionAssessment,

    "types.ImprovedImplementation": types.ImprovedImplementation,
    "stream_types.ImprovedImplementation": stream_types.ImprovedImplementation,

    "types.NewHelperFunction": types.NewHelperFunction,
    "stream_types.NewHelperFunction": stream_types.NewHelperFunction,

    "types.NewToolAnalysis": types.NewToolAnalysis,
    "stream_types.NewToolAnalysis": stream_types.NewToolAnalysis,

    "types.SimilarityResult": types.SimilarityResult,
    "stream_types.SimilarityResult": stream_types.SimilarityResult,

    "types.TestAndImproveError": types.TestAndImproveError,
    "stream_types.TestAndImproveError": stream_types.TestAndImproveError,

    "types.TestAndImproveSuccess": types.TestAndImproveSuccess,
    "stream_types.TestAndImproveSuccess": stream_types.TestAndImproveSuccess,

    "types.ToolCreationResult": types.ToolCreationResult,
    "stream_types.ToolCreationResult": stream_types.ToolCreationResult,

    "types.ToolOptimizationResult": types.ToolOptimizationResult,
    "stream_types.ToolOptimizationResult": stream_types.ToolOptimizationResult,

    "types.UpdatedHelperFunction": types.UpdatedHelperFunction,
    "stream_types.UpdatedHelperFunction": stream_types.UpdatedHelperFunction,


    "types.QuestionCategory": types.QuestionCategory,

}