"""
Generated by Cursor - not reviewd yet.
"""

from smolagents.local_python_executor import (
    BASE_PYTHON_TOOLS,
    LocalPythonExecutor,
)


class PythonExecutorTool:
    def __init__(self, authorized_imports=None, static_tools=None):
        # Set defaults if not provided
        self.authorized_imports = authorized_imports or ["math", "numpy"]
        self.static_tools = static_tools or BASE_PYTHON_TOOLS.copy()
        # Create persistent state
        self.state = {}
        # Initialize executor
        self.executor = LocalPythonExecutor(
            additional_authorized_imports=self.authorized_imports
        )
        self.executor.static_tools = self.static_tools

    def evaluate_python_code(self, code: str) -> str:
        """Execute Python code and return both the result and any printed output.

        Args:
            code: The Python code to execute as a string

        Returns:
            A formatted string containing both the print outputs and return value
        """
        # Execute the code
        result, logs, is_final = self.executor(code)

        # Format the response to include both printed output and return value
        response = ""
        if logs:
            response += f"Print output:\n{logs}\n\n"

        response += f"Return value: {result}"
        return response
